/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCCompatibilityPackedAlignFieldSmallerAlign */
#ifndef _Included_io_vproxy_pni_test_GCCCompatibilityPackedAlignFieldSmallerAlign
#define _Included_io_vproxy_pni_test_GCCCompatibilityPackedAlignFieldSmallerAlign
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "gcc_compatibility.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(GCCCompatibilityPackedAlignFieldSmallerAlign, GCCCompatibilityPackedAlignFieldSmallerAlign *)

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityPackedAlignFieldSmallerAlign_init(PNIEnv_void * env, GCCCompatibilityPackedAlignFieldSmallerAlign * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityPackedAlignFieldSmallerAlign_size(PNIEnv_long * env, GCCCompatibilityPackedAlignFieldSmallerAlign * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCCompatibilityPackedAlignFieldSmallerAlign
// sha256:3dfa3bfd295c01aa13082f9f382f8d2b4702a606f73684dec6507cdda793aa10
