/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_UnionO */
#ifndef _Included_io_vproxy_pni_test_UnionO
#define _Included_io_vproxy_pni_test_UnionO
#ifdef __cplusplus
extern "C" {
#endif

union UnionO;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_UnionP.h"

#ifdef __cplusplus
extern "C" {
#endif

union UnionO {
    int16_t s;
    int32_t i;
    UnionP p;
} PNI_PACKED;

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_UnionO
// sha256:7dbce6d1026e79ed2a2117231587d23c4cfeed6e501b18371dc3df8084eca916
