/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_RefAndFuncFields */
#ifndef _Included_io_vproxy_pni_test_RefAndFuncFields
#define _Included_io_vproxy_pni_test_RefAndFuncFields
#ifdef __cplusplus
extern "C" {
#endif

struct RefAndFuncFields;
typedef struct RefAndFuncFields RefAndFuncFields;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_ObjectStruct.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(RefAndFuncFields, RefAndFuncFields *)

PNI_PACK(struct, RefAndFuncFields, {
    PNIRef * ref;
    PNIRef * ref2;
    PNIRef * ref3;
    PNIFunc * func;
    PNIFunc * func2;
});

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_RefAndFuncFields_call(PNIEnv_void * env, RefAndFuncFields * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_RefAndFuncFields_call2(PNIEnv_void * env, RefAndFuncFields * self, ObjectStruct * o);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_RefAndFuncFields_set(PNIEnv_void * env, RefAndFuncFields * self, PNIRef * ref, PNIRef * ref2, PNIRef * ref3, PNIFunc * func, PNIFunc * func2);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_RefAndFuncFields_setRaw(PNIEnv_void * env, RefAndFuncFields * self, PNIRef * ref, PNIRef * ref2, PNIRef * ref3);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_RefAndFuncFields_retrieveRef(PNIEnv_ref * env, RefAndFuncFields * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_RefAndFuncFields_retrieveRef2(PNIEnv_ref * env, RefAndFuncFields * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_RefAndFuncFields_retrieveRef3(PNIEnv_ref * env, RefAndFuncFields * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_RefAndFuncFields_retrieveFunc(PNIEnv_func * env, RefAndFuncFields * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_RefAndFuncFields_retrieveFunc2(PNIEnv_func * env, RefAndFuncFields * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_RefAndFuncFields
// metadata.generator-version: pni test
// sha256:d5170cd19c2e8cf58b7f2364ae7548f1b8ac8e3c0dfa0d26a6b3145f5e43c2e3
