/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_StructB */
#ifndef _Included_io_vproxy_pni_test_StructB
#define _Included_io_vproxy_pni_test_StructB
#ifdef __cplusplus
extern "C" {
#endif

struct PNI_DUMMY_StructB;
typedef struct PNI_DUMMY_StructB StructB;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_UnionC.h"
#include "io_vproxy_pni_test_StructD.h"
#include "io_vproxy_pni_test_UnionEmbedded.h"

#ifdef __cplusplus
extern "C" {
#endif

struct PNI_DUMMY_StructB {
    int32_t i; int8_t __padding_after_i[4];
    UnionC c;
    int64_t l;
    StructD * d;
    union {
        int32_t n;
        void * seg;
    };
} PNI_PACKED;

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_StructB
// sha256:c8fc711454d178033710be503d062c6a621bd25504c93d17f8cb889fca234337
