/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCCompatibilityAlignFieldPacked */
#ifndef _Included_io_vproxy_pni_test_GCCCompatibilityAlignFieldPacked
#define _Included_io_vproxy_pni_test_GCCCompatibilityAlignFieldPacked
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "gcc_compatibility.h"
#include "io_vproxy_pni_test_GCCCompatibilityPacked.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityAlignFieldPacked_init(PNIEnv_void * env, GCCCompatibilityAlignFieldPacked * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityAlignFieldPacked_size(PNIEnv_long * env, GCCCompatibilityAlignFieldPacked * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCCompatibilityAlignFieldPacked
// sha256:9caeffc63b5f7fe99827b3aa08806a55d2307135782ac4a7df91936def556b01
