/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_BaseClass */
#ifndef _Included_io_vproxy_pni_test_BaseClass
#define _Included_io_vproxy_pni_test_BaseClass
#ifdef __cplusplus
extern "C" {
#endif

struct BaseClass;
typedef struct BaseClass BaseClass;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(BaseClass, BaseClass *)
PNIBufExpand(BaseClass, BaseClass, 1)

PNI_PACK(struct, BaseClass, {
    int8_t a;
});

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_BaseClass_aaa(PNIEnv_void * env, BaseClass * self, int8_t a);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_BaseClass
// metadata.generator-version: pni test
// sha256:e5a34e48176424ed924ab0e38bb5906c956e6a9ab29fe2436564834426620bc7
