/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_AlwaysAlignedGrandChild */
#ifndef _Included_io_vproxy_pni_test_AlwaysAlignedGrandChild
#define _Included_io_vproxy_pni_test_AlwaysAlignedGrandChild
#ifdef __cplusplus
extern "C" {
#endif

struct AlwaysAlignedGrandChild;
typedef struct AlwaysAlignedGrandChild AlwaysAlignedGrandChild;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_AlwaysAlignedChild.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(AlwaysAlignedGrandChild, AlwaysAlignedGrandChild *)
PNIBufExpand(AlwaysAlignedGrandChild, AlwaysAlignedGrandChild, 16)

struct AlwaysAlignedGrandChild {
    AlwaysAlignedChild SUPER;
    int64_t c;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_AlwaysAlignedGrandChild
// metadata.generator-version: pni test
// sha256:9555eda45bfe7a6dafbe79a8d2bec8c5a6428e3785fc3187e343cf17af96d1c7
