/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCCompatibilityUnion */
#ifndef _Included_io_vproxy_pni_test_GCCCompatibilityUnion
#define _Included_io_vproxy_pni_test_GCCCompatibilityUnion
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(GCCCompatibilityUnion, GCCCompatibilityUnion *)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCCompatibilityUnion
// metadata.generator-version: pni test
// sha256:42c30a0c667153f023e406772d108e9ba08ab8c2441916baab17002c4aaa360e
