/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCompatibilityNormalContainUnion */
#ifndef _Included_io_vproxy_pni_test_GCCompatibilityNormalContainUnion
#define _Included_io_vproxy_pni_test_GCCompatibilityNormalContainUnion
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "gcc_compatibility.h"
#include "io_vproxy_pni_test_GCCCompatibilityUnion.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(GCCompatibilityNormalContainUnion, GCCompatibilityNormalContainUnion *)
PNIBufExpand(GCCompatibilityNormalContainUnion, GCCompatibilityNormalContainUnion, 24)

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCompatibilityNormalContainUnion_initB(PNIEnv_void * env, GCCompatibilityNormalContainUnion * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCompatibilityNormalContainUnion_initS(PNIEnv_void * env, GCCompatibilityNormalContainUnion * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCompatibilityNormalContainUnion_initN(PNIEnv_void * env, GCCompatibilityNormalContainUnion * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCompatibilityNormalContainUnion_initF(PNIEnv_void * env, GCCompatibilityNormalContainUnion * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCompatibilityNormalContainUnion_initD(PNIEnv_void * env, GCCompatibilityNormalContainUnion * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCompatibilityNormalContainUnion_initL(PNIEnv_void * env, GCCompatibilityNormalContainUnion * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCompatibilityNormalContainUnion_size(PNIEnv_long * env, GCCompatibilityNormalContainUnion * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCompatibilityNormalContainUnion
// metadata.generator-version: pni test
// sha256:9f64043c37364849d9f7f5eb8b28a3897e3bf497ff87e0900ede5ee2ff12f9d0
