/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_AlwaysAlignedBase */
#ifndef _Included_io_vproxy_pni_test_AlwaysAlignedBase
#define _Included_io_vproxy_pni_test_AlwaysAlignedBase
#ifdef __cplusplus
extern "C" {
#endif

struct AlwaysAlignedBase;
typedef struct AlwaysAlignedBase AlwaysAlignedBase;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(AlwaysAlignedBase, AlwaysAlignedBase *)

PNI_PACK(struct, AlwaysAlignedBase, {
    int8_t a;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_AlwaysAlignedBase
// metadata.generator-version: pni test
// sha256:92fd6ac63b5a2d3d771609a51b86dc4f1fae0b4f60a1cfeb6a6ee99d7fd3da18
