/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCCompatibilityNormal */
#ifndef _Included_io_vproxy_pni_test_GCCCompatibilityNormal
#define _Included_io_vproxy_pni_test_GCCCompatibilityNormal
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "gcc_compatibility.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(GCCCompatibilityNormal, GCCCompatibilityNormal *)

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityNormal_init(PNIEnv_void * env, GCCCompatibilityNormal * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityNormal_size(PNIEnv_long * env, GCCCompatibilityNormal * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCCompatibilityNormal
// sha256:b75855d2a2923d6171ea15388bef8edad0d6cf2f41b84b269d089098e32b76d0
