/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCCompatibilityPacked */
#ifndef _Included_io_vproxy_pni_test_GCCCompatibilityPacked
#define _Included_io_vproxy_pni_test_GCCCompatibilityPacked
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "gcc_compatibility.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(GCCCompatibilityPacked, GCCCompatibilityPacked *)

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityPacked_init(PNIEnv_void * env, GCCCompatibilityPacked * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityPacked_size(PNIEnv_long * env, GCCCompatibilityPacked * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCCompatibilityPacked
// sha256:7a9984b2826b91f69a53b24e846a1d5e139a6c0b76fd959e74c55967545edf81
