/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_ChildOfPacked */
#ifndef _Included_io_vproxy_pni_test_ChildOfPacked
#define _Included_io_vproxy_pni_test_ChildOfPacked
#ifdef __cplusplus
extern "C" {
#endif

struct ChildOfPacked;
typedef struct ChildOfPacked ChildOfPacked;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_PackedBaseClass.h"
#include "io_vproxy_pni_test_ObjectStruct.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(ChildOfPacked, ChildOfPacked *)

PNI_PACK(struct, ChildOfPacked, {
    PackedBaseClass SUPER;
     /* padding */ uint64_t :8;
    int32_t x;
    ObjectStruct o;
});

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_ChildOfPacked_xxx(PNIEnv_void * env, ChildOfPacked * self, int32_t x);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_ChildOfPacked_ooo(PNIEnv_void * env, ChildOfPacked * self, ObjectStruct * o);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_ChildOfPacked
// metadata.generator-version: pni test
// sha256:442e3de03e5784c866bfa7ae941bc77c8e4c8197390eb4a8142742e44dbea000
