/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_StructB */
#ifndef _Included_io_vproxy_pni_test_StructB
#define _Included_io_vproxy_pni_test_StructB
#ifdef __cplusplus
extern "C" {
#endif

struct StructB;
typedef struct StructB StructB;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_UnionC.h"
#include "io_vproxy_pni_test_StructD.h"
#include "io_vproxy_pni_test_UnionEmbedded.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(StructB, StructB *)
PNIBufExpand(StructB, StructB, 40)

PNI_PACK(struct, StructB, {
    int32_t i; /* padding */ uint32_t : 32;
    UnionC c;
    int64_t l;
    StructD * d;
    union {
        int32_t n;
        void * seg;
    };
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_StructB
// metadata.generator-version: pni test
// sha256:b22f3610c53062d126f4121d02141865c1f371caba0da41e97d9de31f3603f20
