/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCCompatibilityNonPackedArray */
#ifndef _Included_io_vproxy_pni_test_GCCCompatibilityNonPackedArray
#define _Included_io_vproxy_pni_test_GCCCompatibilityNonPackedArray
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "gcc_compatibility.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityNonPackedArray_init(PNIEnv_void * env, GCCCompatibilityNonPackedArray * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityNonPackedArray_size(PNIEnv_long * env, GCCCompatibilityNonPackedArray * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCCompatibilityNonPackedArray
// sha256:cb4874204c60d83acfc9f55c04feff1b2111fbeb84694c89b22676d81d5110a2
