/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCCompatibilityPackedArray */
#ifndef _Included_io_vproxy_pni_test_GCCCompatibilityPackedArray
#define _Included_io_vproxy_pni_test_GCCCompatibilityPackedArray
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "gcc_compatibility.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(GCCCompatibilityPackedArray, GCCCompatibilityPackedArray *)
PNIBufExpand(GCCCompatibilityPackedArray, GCCCompatibilityPackedArray, 60)

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityPackedArray_init(PNIEnv_void * env, GCCCompatibilityPackedArray * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityPackedArray_size(PNIEnv_long * env, GCCCompatibilityPackedArray * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCCompatibilityPackedArray
// metadata.generator-version: pni test
// sha256:2e691dc486939f30c7dcdc29da53c9a35898b91664ba6ae1b4269287d46123cb
