/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCCompatibilityAlignFieldPacked */
#ifndef _Included_io_vproxy_pni_test_GCCCompatibilityAlignFieldPacked
#define _Included_io_vproxy_pni_test_GCCCompatibilityAlignFieldPacked
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "gcc_compatibility.h"
#include "io_vproxy_pni_test_GCCCompatibilityPacked.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(GCCCompatibilityAlignFieldPacked, GCCCompatibilityAlignFieldPacked *)

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityAlignFieldPacked_init(PNIEnv_void * env, GCCCompatibilityAlignFieldPacked * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityAlignFieldPacked_size(PNIEnv_long * env, GCCCompatibilityAlignFieldPacked * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCCompatibilityAlignFieldPacked
// metadata.generator-version: pni test
// sha256:e4506557ace47888142e1b287759e74c02a9b72061dba6e23e459f86eb568766
