/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_AlwaysAlignedChild */
#ifndef _Included_io_vproxy_pni_test_AlwaysAlignedChild
#define _Included_io_vproxy_pni_test_AlwaysAlignedChild
#ifdef __cplusplus
extern "C" {
#endif

struct AlwaysAlignedChild;
typedef struct AlwaysAlignedChild AlwaysAlignedChild;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_AlwaysAlignedBase.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(AlwaysAlignedChild, AlwaysAlignedChild *)

PNI_PACK(struct, AlwaysAlignedChild, {
    AlwaysAlignedBase SUPER;
     /* padding */ uint64_t :8;
    int16_t b;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_AlwaysAlignedChild
// metadata.generator-version: pni test
// sha256:62f9c663fceff2ec38783c009dc587311d1fff8a7fa5e9c0a85802bca12371b3
