/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_AlwaysAlignedGrandChild */
#ifndef _Included_io_vproxy_pni_test_AlwaysAlignedGrandChild
#define _Included_io_vproxy_pni_test_AlwaysAlignedGrandChild
#ifdef __cplusplus
extern "C" {
#endif

struct AlwaysAlignedGrandChild;
typedef struct AlwaysAlignedGrandChild AlwaysAlignedGrandChild;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_AlwaysAlignedChild.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(AlwaysAlignedGrandChild, AlwaysAlignedGrandChild *)
PNIBufExpand(AlwaysAlignedGrandChild, AlwaysAlignedGrandChild, 16)

PNI_PACK(struct, AlwaysAlignedGrandChild, {
    AlwaysAlignedChild SUPER;
     /* padding */ uint32_t : 32;
    int64_t c;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_AlwaysAlignedGrandChild
// metadata.generator-version: pni test
// sha256:74f79c49588df12a84b7be23772d3340a40783e9307e3f831c130135ffa26a6a
