/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_StructM */
#ifndef _Included_io_vproxy_pni_test_StructM
#define _Included_io_vproxy_pni_test_StructM
#ifdef __cplusplus
extern "C" {
#endif

struct StructM;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_StructN.h"

#ifdef __cplusplus
extern "C" {
#endif

struct StructM {
    struct N_st n_st; int8_t __padding_after_n_st[6];
} PNI_PACKED;

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_StructM_nnn(PNIEnv_void * env, struct StructM * self, struct N_st * n_st);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_StructM
// sha256:97402b73dd88ff1a422a365bf66f2cb059c50fb9b5684d954389763ce184d894
