/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_StructM */
#ifndef _Included_io_vproxy_pni_test_StructM
#define _Included_io_vproxy_pni_test_StructM
#ifdef __cplusplus
extern "C" {
#endif

struct StructM;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_StructN.h"

#ifdef __cplusplus
extern "C" {
#endif

PNI_PACK(struct, StructM, {
    struct N_st n_st;
});

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_StructM_nnn(PNIEnv_void * env, struct StructM * self, struct N_st * n_st);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_StructM
// sha256:99ded4e832b2f8f6767c3c1778d88bee4838a0bf67dbe3e0f2789789904a5cf3
