/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCCompatibilityNormal */
#ifndef _Included_io_vproxy_pni_test_GCCCompatibilityNormal
#define _Included_io_vproxy_pni_test_GCCCompatibilityNormal
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "gcc_compatibility.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(GCCCompatibilityNormal, GCCCompatibilityNormal *)
PNIBufExpand(GCCCompatibilityNormal, GCCCompatibilityNormal, 32)

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityNormal_init(PNIEnv_void * env, GCCCompatibilityNormal * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityNormal_size(PNIEnv_long * env, GCCCompatibilityNormal * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCCompatibilityNormal
// metadata.generator-version: pni test
// sha256:b55f3c159211feed607fc159b6a958beff302bc6cfc036c0f920e442fa58e009
