/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_SizeofStructExpr */
#ifndef _Included_io_vproxy_pni_test_SizeofStructExpr
#define _Included_io_vproxy_pni_test_SizeofStructExpr
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "sizeof.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT size_t JNICALL JavaCritical_io_vproxy_pni_test_SizeofStructExpr___getLayoutByteSize();

PNIEnvExpand(SizeofStructExpr, SizeofStructExpr *)
PNIBufExpand(SizeofStructExpr, SizeofStructExpr, JavaCritical_io_vproxy_pni_test_SizeofStructExpr___getLayoutByteSize())

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_SizeofStructExpr
// metadata.generator-version: pni test
// sha256:6bba9f20403b346456a31ef26d9035117181a4e08b8a6403ec3722dd4cfde78a
