/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_LargeAlignBase */
#ifndef _Included_io_vproxy_pni_test_LargeAlignBase
#define _Included_io_vproxy_pni_test_LargeAlignBase
#ifdef __cplusplus
extern "C" {
#endif

struct LargeAlignBase;
typedef struct LargeAlignBase LargeAlignBase;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(LargeAlignBase, LargeAlignBase *)
PNIBufExpand(LargeAlignBase, LargeAlignBase, 8)

PNI_PACK(struct, LargeAlignBase, {
    int64_t x;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_LargeAlignBase
// metadata.generator-version: pni test
// sha256:6d9ade01724a3ad68bae13f8aaf381988076383b19055b72bb6c46f098f4000a
