/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_ObjectStruct */
#ifndef _Included_io_vproxy_pni_test_ObjectStruct
#define _Included_io_vproxy_pni_test_ObjectStruct
#ifdef __cplusplus
extern "C" {
#endif

struct ObjectStruct;
typedef struct ObjectStruct ObjectStruct;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(ObjectStruct, ObjectStruct *)

PNI_PACK(struct, ObjectStruct, {
    char * str;
    char lenStr[16];
    void * seg;
    PNIBuf buf;
});

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_ObjectStruct_func1(PNIEnv_void * env, ObjectStruct * self, char * str, char * str2, void * seg, PNIBuf * buf);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_pni_test_ObjectStruct_func1Critical(ObjectStruct * self, char * str, char * str2, void * seg, PNIBuf * buf);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_ObjectStruct_retrieveStr(PNIEnv_string * env, ObjectStruct * self);
JNIEXPORT char * JNICALL JavaCritical_io_vproxy_pni_test_ObjectStruct_retrieveStrCritical(ObjectStruct * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_ObjectStruct_retrieveLenStr(PNIEnv_string * env, ObjectStruct * self);
JNIEXPORT char * JNICALL JavaCritical_io_vproxy_pni_test_ObjectStruct_retrieveLenStrCritical(ObjectStruct * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_ObjectStruct_retrieveSeg(PNIEnv_pointer * env, ObjectStruct * self);
JNIEXPORT void * JNICALL JavaCritical_io_vproxy_pni_test_ObjectStruct_retrieveSegCritical(ObjectStruct * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_ObjectStruct_retrieveBuf(PNIEnv_buf * env, ObjectStruct * self);
JNIEXPORT PNIBuf * JNICALL JavaCritical_io_vproxy_pni_test_ObjectStruct_retrieveBufCritical(ObjectStruct * self, PNIBuf * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_ObjectStruct_checkPointerSetToNonNull(PNIEnv_bool * env, ObjectStruct * self);
JNIEXPORT uint8_t JNICALL JavaCritical_io_vproxy_pni_test_ObjectStruct_checkPointerSetToNonNullCritical(ObjectStruct * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_ObjectStruct_checkPointerSetToNull(PNIEnv_bool * env, ObjectStruct * self);
JNIEXPORT uint8_t JNICALL JavaCritical_io_vproxy_pni_test_ObjectStruct_checkPointerSetToNullCritical(ObjectStruct * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_ObjectStruct
// sha256:04faee6437cf29c2eb3944159730115266e3215e2745679cf8e2e649ab6d0722
