/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_UnionO */
#ifndef _Included_io_vproxy_pni_test_UnionO
#define _Included_io_vproxy_pni_test_UnionO
#ifdef __cplusplus
extern "C" {
#endif

union UnionO;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_UnionP.h"

#ifdef __cplusplus
extern "C" {
#endif

PNI_PACK(union, UnionO, {
    int16_t s;
    int32_t i;
    UnionP p;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_UnionO
// sha256:db4869c374b9facddd47dadb26c2c4bf6db5797d2aaff8d375039b9cd9f7f4b3
