/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCCompatibilityAlignField */
#ifndef _Included_io_vproxy_pni_test_GCCCompatibilityAlignField
#define _Included_io_vproxy_pni_test_GCCCompatibilityAlignField
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "gcc_compatibility.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(GCCCompatibilityAlignField, GCCCompatibilityAlignField *)
PNIBufExpand(GCCCompatibilityAlignField, GCCCompatibilityAlignField, 12)

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityAlignField_init(PNIEnv_void * env, GCCCompatibilityAlignField * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityAlignField_size(PNIEnv_long * env, GCCCompatibilityAlignField * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCCompatibilityAlignField
// metadata.generator-version: pni test
// sha256:5de0100c49c50039e8d706181f00c292966685da2ba8d6376a220ea93d28d6b2
