/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCCompatibilityNonPackedArray */
#ifndef _Included_io_vproxy_pni_test_GCCCompatibilityNonPackedArray
#define _Included_io_vproxy_pni_test_GCCCompatibilityNonPackedArray
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "gcc_compatibility.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(GCCCompatibilityNonPackedArray, GCCCompatibilityNonPackedArray *)
PNIBufExpand(GCCCompatibilityNonPackedArray, GCCCompatibilityNonPackedArray, 80)

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityNonPackedArray_init(PNIEnv_void * env, GCCCompatibilityNonPackedArray * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityNonPackedArray_size(PNIEnv_long * env, GCCCompatibilityNonPackedArray * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCCompatibilityNonPackedArray
// metadata.generator-version: pni test
// sha256:9a558e50a9da5a5f875d338c57ba751bd61e41095bd3979429e291c04eccd3ba
