/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_StructN */
#ifndef _Included_io_vproxy_pni_test_StructN
#define _Included_io_vproxy_pni_test_StructN
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_StructUnionAnnotation.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(N_st, struct N_st *)

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_StructN_retrieveS(PNIEnv_short * env, struct N_st * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_StructN_retrieveL(PNIEnv_long * env, struct N_st * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_StructN
// sha256:bbaad5de0420bd4d169cacd53c9dc1708740e70698ec795de4d2af04f3d5b869
