/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_KtDowncall */
#ifndef _Included_io_vproxy_pni_test_KtDowncall
#define _Included_io_vproxy_pni_test_KtDowncall
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_KtStruct.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int64_t JNICALL JavaCritical_io_vproxy_pni_test_KtDowncall_retrieveLong(KtStruct * o);
JNIEXPORT KtStruct * JNICALL JavaCritical_io_vproxy_pni_test_KtDowncall_invokeHelloWorld(int32_t i, int64_t l, KtStruct * return_);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_KtDowncall
// metadata.generator-version: pni test
// sha256:d77fdf36a6537a49873b08c306383f6102e2b3d1e77eccb9daf629461ae7f494
