/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCCompatibilityArrayZero */
#ifndef _Included_io_vproxy_pni_test_GCCCompatibilityArrayZero
#define _Included_io_vproxy_pni_test_GCCCompatibilityArrayZero
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "gcc_compatibility.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(GCCCompatibilityArrayZero, GCCCompatibilityArrayZero *)
PNIBufExpand(GCCCompatibilityArrayZero, GCCCompatibilityArrayZero, 16)

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityArrayZero_init(PNIEnv_void * env, GCCCompatibilityArrayZero * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityArrayZero_size(PNIEnv_long * env, GCCCompatibilityArrayZero * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCCompatibilityArrayZero
// metadata.generator-version: pni test
// sha256:94f0aa708cbe3b51a0f309f5ef0490308dccb920e2ede8fc84c920b5e9f0d5d1
