/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_UnionP */
#ifndef _Included_io_vproxy_pni_test_UnionP
#define _Included_io_vproxy_pni_test_UnionP
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_StructUnionAnnotation.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int JNICALL UnionP_retrieve_i(PNIEnv_int * env, UnionP * self);
JNIEXPORT int JNICALL UnionP_retrieve_l(PNIEnv_long * env, UnionP * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_UnionP
// sha256:d7396983e53a8b753c984b98743a8bfc99a5ed62001f7fafca7867e242133a73
