/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_UnionC */
#ifndef _Included_io_vproxy_pni_test_UnionC
#define _Included_io_vproxy_pni_test_UnionC
#ifdef __cplusplus
extern "C" {
#endif

union UnionC;
typedef union UnionC UnionC;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(UnionC, UnionC *)
PNIBufExpand(UnionC, UnionC, 8)

PNI_PACK(union, UnionC, {
    int32_t n;
    int64_t l;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_UnionC
// metadata.generator-version: pni test
// sha256:01fabb1aa79684bb224323d29265d428870463ede0a7b3eb16f3ec09b517e9a5
