/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCompatibilityNormalContainUnion */
#ifndef _Included_io_vproxy_pni_test_GCCompatibilityNormalContainUnion
#define _Included_io_vproxy_pni_test_GCCompatibilityNormalContainUnion
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "gcc_compatibility.h"
#include "io_vproxy_pni_test_GCCCompatibilityUnion.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(GCCompatibilityNormalContainUnion, GCCompatibilityNormalContainUnion *)

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCompatibilityNormalContainUnion_initB(PNIEnv_void * env, GCCompatibilityNormalContainUnion * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCompatibilityNormalContainUnion_initS(PNIEnv_void * env, GCCompatibilityNormalContainUnion * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCompatibilityNormalContainUnion_initN(PNIEnv_void * env, GCCompatibilityNormalContainUnion * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCompatibilityNormalContainUnion_initF(PNIEnv_void * env, GCCompatibilityNormalContainUnion * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCompatibilityNormalContainUnion_initD(PNIEnv_void * env, GCCompatibilityNormalContainUnion * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCompatibilityNormalContainUnion_initL(PNIEnv_void * env, GCCompatibilityNormalContainUnion * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCompatibilityNormalContainUnion_size(PNIEnv_long * env, GCCompatibilityNormalContainUnion * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCompatibilityNormalContainUnion
// metadata.generator-version: pni test
// sha256:c5d95ac3af62cb852051aeffe0571d8ccffa2781bd144604ed5a141ec0d1c64a
