/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_ChildOfLargeAlign */
#ifndef _Included_io_vproxy_pni_test_ChildOfLargeAlign
#define _Included_io_vproxy_pni_test_ChildOfLargeAlign
#ifdef __cplusplus
extern "C" {
#endif

struct ChildOfLargeAlign;
typedef struct ChildOfLargeAlign ChildOfLargeAlign;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_LargeAlignBase.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(ChildOfLargeAlign, ChildOfLargeAlign *)
PNIBufExpand(ChildOfLargeAlign, ChildOfLargeAlign, 16)

struct ChildOfLargeAlign {
    LargeAlignBase SUPER;
    int8_t y;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_ChildOfLargeAlign
// metadata.generator-version: pni test
// sha256:1a012921bca9c4eea3de512ad93848f227111048b2a72c4636bb7aa623f5e825
