/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_ToStringUnion */
#ifndef _Included_io_vproxy_pni_test_ToStringUnion
#define _Included_io_vproxy_pni_test_ToStringUnion
#ifdef __cplusplus
extern "C" {
#endif

union ToStringUnion;
typedef union ToStringUnion ToStringUnion;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_ToStringClass.h"
#include "io_vproxy_pni_test_ToStringClass2.h"
#include "io_vproxy_pni_test_ToStringClassRecurse.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(ToStringUnion, ToStringUnion *)
PNIBufExpand(ToStringUnion, ToStringUnion, 40)

union ToStringUnion {
    int64_t num;
    ToStringClass c1;
    ToStringClass2 c2;
    ToStringClassRecurse cr;
    ToStringClass * pc1;
    ToStringClass2 * pc2;
    ToStringClassRecurse * pcr;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_ToStringUnion
// metadata.generator-version: pni test
// sha256:51d0bdcbe49885b6b4f4595fd7a256b9eb962a42661415a14134ffa8a1d8f0c8
