/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_StructD */
#ifndef _Included_io_vproxy_pni_test_StructD
#define _Included_io_vproxy_pni_test_StructD
#ifdef __cplusplus
extern "C" {
#endif

struct StructD;
typedef struct StructD StructD;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(StructD, StructD *)
PNIBufExpand(StructD, StructD, 16)

PNI_PACK(struct, StructD, {
    int32_t n; /* padding */ uint32_t : 32;
    double d;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_StructD
// metadata.generator-version: pni test
// sha256:29f6ea593eda59ae3cb980defeb6352dd863e01c188f73655f58e135ff906a5b
