/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_UnionC */
#ifndef _Included_io_vproxy_pni_test_UnionC
#define _Included_io_vproxy_pni_test_UnionC
#ifdef __cplusplus
extern "C" {
#endif

union PNI_DUMMY_UnionC;
typedef union PNI_DUMMY_UnionC UnionC;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

union PNI_DUMMY_UnionC {
    int32_t n;
    int64_t l;
} PNI_PACKED;

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_UnionC
// sha256:f1c27eafe30ca0d2e16849f8767d4c8014336124325c92098e4ad4ef12a3ca0d
