/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_ChildClass */
#ifndef _Included_io_vproxy_pni_test_ChildClass
#define _Included_io_vproxy_pni_test_ChildClass
#ifdef __cplusplus
extern "C" {
#endif

struct ChildClass;
typedef struct ChildClass ChildClass;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_BaseClass.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(ChildClass, ChildClass *)
PNIBufExpand(ChildClass, ChildClass, 4)

PNI_PACK(struct, ChildClass, {
    BaseClass SUPER;
     /* padding */ uint64_t :8;
    int16_t x;
});

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_ChildClass_xxx(PNIEnv_void * env, ChildClass * self, int16_t x);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_ChildClass
// metadata.generator-version: pni test
// sha256:c314a6adc5941ff24d3947c6d465bb01f6594040c0c1d27e9176196903f368ba
