/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_ChildOfPacked */
#ifndef _Included_io_vproxy_pni_test_ChildOfPacked
#define _Included_io_vproxy_pni_test_ChildOfPacked
#ifdef __cplusplus
extern "C" {
#endif

struct ChildOfPacked;
typedef struct ChildOfPacked ChildOfPacked;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_PackedBaseClass.h"
#include "io_vproxy_pni_test_ObjectStruct.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(ChildOfPacked, ChildOfPacked *)
PNIBufExpand(ChildOfPacked, ChildOfPacked, 56)

PNI_PACK(struct, ChildOfPacked, {
    PackedBaseClass SUPER;
     /* padding */ uint8_t : 8;
    int32_t x;
    ObjectStruct o;
});

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_ChildOfPacked_xxx(PNIEnv_void * env, ChildOfPacked * self, int32_t x);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_ChildOfPacked_ooo(PNIEnv_void * env, ChildOfPacked * self, ObjectStruct * o);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_ChildOfPacked
// metadata.generator-version: pni test
// sha256:a1a68cd535af54bcb81d2d04a8f45c671af93e45a7ac13862ece565747eb3d8b
