/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_UnionP */
#ifndef _Included_io_vproxy_pni_test_UnionP
#define _Included_io_vproxy_pni_test_UnionP
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_StructUnionAnnotation.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(UnionP, UnionP *)

JNIEXPORT int JNICALL UnionP_retrieve_i(PNIEnv_int * env, UnionP * self);
JNIEXPORT int JNICALL UnionP_retrieve_l(PNIEnv_long * env, UnionP * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_UnionP
// sha256:1811337a7a2090f5a3e957f3d637b8f34b3d3cbbf97da65474477d64ba045e46
