/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_SizeofStruct */
#ifndef _Included_io_vproxy_pni_test_SizeofStruct
#define _Included_io_vproxy_pni_test_SizeofStruct
#ifdef __cplusplus
extern "C" {
#endif

struct SizeofStruct;
typedef struct SizeofStruct SizeofStruct;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT size_t JNICALL JavaCritical_io_vproxy_pni_test_SizeofStruct___getLayoutByteSize();

PNIEnvExpand(SizeofStruct, SizeofStruct *)
PNIBufExpand(SizeofStruct, SizeofStruct, JavaCritical_io_vproxy_pni_test_SizeofStruct___getLayoutByteSize())

PNI_PACK(struct, SizeofStruct, {
    int32_t a;
    int16_t b; /* padding */ uint64_t :16;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_SizeofStruct
// metadata.generator-version: pni test
// sha256:4a70495cb4d3e69fe4a0bcae700aa6f9705056e0b1d9b5771303697f61d6a937
