/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_AlwaysAlignedGrandChild */
#ifndef _Included_io_vproxy_pni_test_AlwaysAlignedGrandChild
#define _Included_io_vproxy_pni_test_AlwaysAlignedGrandChild
#ifdef __cplusplus
extern "C" {
#endif

struct AlwaysAlignedGrandChild;
typedef struct AlwaysAlignedGrandChild AlwaysAlignedGrandChild;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_AlwaysAlignedChild.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(AlwaysAlignedGrandChild, AlwaysAlignedGrandChild *)
PNIBufExpand(AlwaysAlignedGrandChild, AlwaysAlignedGrandChild, 32)

struct AlwaysAlignedGrandChild {
    AlwaysAlignedChild SUPER;
    int64_t c;
    int32_t array[3];
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_AlwaysAlignedGrandChild
// metadata.generator-version: pni test
// sha256:8e0c9b596a6239b852d18bc988252aaac6463e37543b1ef2c0d46bfce2973239
