/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_EmptyChild */
#ifndef _Included_io_vproxy_pni_test_EmptyChild
#define _Included_io_vproxy_pni_test_EmptyChild
#ifdef __cplusplus
extern "C" {
#endif

struct EmptyChild;
typedef struct EmptyChild EmptyChild;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_LargeAlignBase.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(EmptyChild, EmptyChild *)
PNIBufExpand(EmptyChild, EmptyChild, 8)

struct EmptyChild {
    LargeAlignBase SUPER;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_EmptyChild
// metadata.generator-version: pni test
// sha256:f091e8889ea77137a08bc2c3cee020d7266ca0ab9442c63f233cfb7c21508d8d
