/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_AlwaysAlignedChild */
#ifndef _Included_io_vproxy_pni_test_AlwaysAlignedChild
#define _Included_io_vproxy_pni_test_AlwaysAlignedChild
#ifdef __cplusplus
extern "C" {
#endif

struct AlwaysAlignedChild;
typedef struct AlwaysAlignedChild AlwaysAlignedChild;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_AlwaysAlignedBase.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(AlwaysAlignedChild, AlwaysAlignedChild *)
PNIBufExpand(AlwaysAlignedChild, AlwaysAlignedChild, 4)

PNI_PACK(struct, AlwaysAlignedChild, {
    AlwaysAlignedBase SUPER;
     /* padding */ uint8_t : 8;
    int16_t b;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_AlwaysAlignedChild
// metadata.generator-version: pni test
// sha256:a4a78e63fc6c2dec3135d8a7c4d22cc92ac590b133d505419585bd627b30fba6
