/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_LargeAlignBase */
#ifndef _Included_io_vproxy_pni_test_LargeAlignBase
#define _Included_io_vproxy_pni_test_LargeAlignBase
#ifdef __cplusplus
extern "C" {
#endif

struct LargeAlignBase;
typedef struct LargeAlignBase LargeAlignBase;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(LargeAlignBase, LargeAlignBase *)

PNI_PACK(struct, LargeAlignBase, {
    int64_t x;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_LargeAlignBase
// metadata.generator-version: pni test
// sha256:04a12eb3571764bc617524cd761350febf42124e707208cd75f435ac7fd293ef
