/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_Userdata */
#ifndef _Included_io_vproxy_pni_test_Userdata
#define _Included_io_vproxy_pni_test_Userdata
#ifdef __cplusplus
extern "C" {
#endif

struct Userdata;
typedef struct Userdata Userdata;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(Userdata, Userdata *)
PNIBufExpand(Userdata, Userdata, 24)

struct Userdata {
    int32_t x;
    int64_t y;
    int16_t z;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_Userdata
// metadata.generator-version: pni test
// sha256:bf76395673d4b6b392185070fb0ebfb30316b8b1cdd7f9f554569ae8bb6662c2
