/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_SizeofEmbed */
#ifndef _Included_io_vproxy_pni_test_SizeofEmbed
#define _Included_io_vproxy_pni_test_SizeofEmbed
#ifdef __cplusplus
extern "C" {
#endif

struct SizeofEmbed;
typedef struct SizeofEmbed SizeofEmbed;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_SizeofUnion.h"
#include "io_vproxy_pni_test_SizeofStructExpr.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT size_t JNICALL JavaCritical_io_vproxy_pni_test_SizeofEmbed___getLayoutByteSize();

PNIEnvExpand(SizeofEmbed, SizeofEmbed *)
PNIBufExpand(SizeofEmbed, SizeofEmbed, JavaCritical_io_vproxy_pni_test_SizeofEmbed___getLayoutByteSize())

PNI_PACK(struct, SizeofEmbed, {
    int8_t x; /* padding */ uint32_t : 32; uint16_t : 16; uint8_t : 8;
    SizeofUnion * un;
    SizeofStructExpr st;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_SizeofEmbed
// metadata.generator-version: pni test
// sha256:d0a4fdc21e1683da1a5c25329c34d8222dc55255dfdb263fa099a0074e44a313
