/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCCompatibilityPackedAlignField */
#ifndef _Included_io_vproxy_pni_test_GCCCompatibilityPackedAlignField
#define _Included_io_vproxy_pni_test_GCCCompatibilityPackedAlignField
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "gcc_compatibility.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityPackedAlignField_init(PNIEnv_void * env, GCCCompatibilityPackedAlignField * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityPackedAlignField_size(PNIEnv_long * env, GCCCompatibilityPackedAlignField * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCCompatibilityPackedAlignField
// sha256:92f79a08d0c7b9e514e73f2d7fa44e61b6fb0b9ca4b72d745352edc4fe90fabd
