/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_SizeofStruct */
#ifndef _Included_io_vproxy_pni_test_SizeofStruct
#define _Included_io_vproxy_pni_test_SizeofStruct
#ifdef __cplusplus
extern "C" {
#endif

struct SizeofStruct;
typedef struct SizeofStruct SizeofStruct;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT size_t JNICALL JavaCritical_io_vproxy_pni_test_SizeofStruct___getLayoutByteSize();

PNIEnvExpand(SizeofStruct, SizeofStruct *)
PNIBufExpand(SizeofStruct, SizeofStruct, JavaCritical_io_vproxy_pni_test_SizeofStruct___getLayoutByteSize())

struct SizeofStruct {
    int32_t a;
    int16_t b;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_SizeofStruct
// metadata.generator-version: pni test
// sha256:7d0fcfbd97f47a488c8dd8cf244dabd450ea1fb6ca876db166fbd7ce98fb3087
