/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_AlwaysAlignedClass */
#ifndef _Included_io_vproxy_pni_test_AlwaysAlignedClass
#define _Included_io_vproxy_pni_test_AlwaysAlignedClass
#ifdef __cplusplus
extern "C" {
#endif

struct AlwaysAlignedClass;
typedef struct AlwaysAlignedClass AlwaysAlignedClass;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(AlwaysAlignedClass, AlwaysAlignedClass *)

PNI_PACK(struct, AlwaysAlignedClass, {
    int8_t a; /* padding */ uint64_t :8;
    int16_t b; /* padding */ uint64_t :32;
    int64_t c;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_AlwaysAlignedClass
// metadata.generator-version: pni test
// sha256:175f3f8bb505e8ef5705ea5929f7740afc3dd079b3ac75b8da7cbd37fa92f37a
