/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_AlwaysAlignedSizeof */
#ifndef _Included_io_vproxy_pni_test_AlwaysAlignedSizeof
#define _Included_io_vproxy_pni_test_AlwaysAlignedSizeof
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "sizeof.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT size_t JNICALL JavaCritical_io_vproxy_pni_test_AlwaysAlignedSizeof___getLayoutByteSize();

PNIEnvExpand(SizeofStructExpr, SizeofStructExpr *)
PNIBufExpand(SizeofStructExpr, SizeofStructExpr, JavaCritical_io_vproxy_pni_test_AlwaysAlignedSizeof___getLayoutByteSize())

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_AlwaysAlignedSizeof
// metadata.generator-version: pni test
// sha256:fdbb45df7d233df9f0d5bf4cbc281b68a4e1614ac12467b29c06cc2a070c4e0f
