/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCCompatibilityNonPackedContainNonPacked */
#ifndef _Included_io_vproxy_pni_test_GCCCompatibilityNonPackedContainNonPacked
#define _Included_io_vproxy_pni_test_GCCCompatibilityNonPackedContainNonPacked
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "gcc_compatibility.h"
#include "io_vproxy_pni_test_GCCCompatibilityNormal.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityNonPackedContainNonPacked_init(PNIEnv_void * env, GCCCompatibilityNonPackedContainNonPacked * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityNonPackedContainNonPacked_size(PNIEnv_long * env, GCCCompatibilityNonPackedContainNonPacked * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCCompatibilityNonPackedContainNonPacked
// sha256:38716d1fafbb039694eca88b37a46f0a2674ce2513fd96e1c46c808a027b1711
