/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_AlignBaseClass */
#ifndef _Included_io_vproxy_pni_test_AlignBaseClass
#define _Included_io_vproxy_pni_test_AlignBaseClass
#ifdef __cplusplus
extern "C" {
#endif

struct AlignBaseClass;
typedef struct AlignBaseClass AlignBaseClass;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(AlignBaseClass, AlignBaseClass *)
PNIBufExpand(AlignBaseClass, AlignBaseClass, 2)

struct AlignBaseClass {
    int16_t a;
};

JNIEXPORT int16_t JNICALL JavaCritical_io_vproxy_pni_test_AlignBaseClass_aaaa(AlignBaseClass * self);
JNIEXPORT int64_t JNICALL JavaCritical_io_vproxy_pni_test_AlignBaseClass_size0(AlignBaseClass * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_AlignBaseClass
// metadata.generator-version: pni test
// sha256:d56aa3891d31b8216b59cd19299f4435ddc26d7387e8412592ed2effdad94e69
