/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_SizeofEmbed */
#ifndef _Included_io_vproxy_pni_test_SizeofEmbed
#define _Included_io_vproxy_pni_test_SizeofEmbed
#ifdef __cplusplus
extern "C" {
#endif

struct SizeofEmbed;
typedef struct SizeofEmbed SizeofEmbed;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_SizeofUnion.h"
#include "io_vproxy_pni_test_SizeofStructExpr.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(SizeofEmbed, SizeofEmbed *)

PNI_PACK(struct, SizeofEmbed, {
    int8_t x; /* padding */ uint64_t :56;
    SizeofUnion * un;
    SizeofStructExpr st;
});

JNIEXPORT size_t JNICALL JavaCritical_io_vproxy_pni_test_SizeofEmbed___getLayoutByteSize();

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_SizeofEmbed
// metadata.generator-version: pni test
// sha256:bc4ce08bbb41639a23eee49368c3cb4c0c960e9f99591540afb88e835276e04e
