/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_AlignField2 */
#ifndef _Included_io_vproxy_pni_test_AlignField2
#define _Included_io_vproxy_pni_test_AlignField2
#ifdef __cplusplus
extern "C" {
#endif

struct AlignField2;
typedef struct AlignField2 AlignField2;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(AlignField2, AlignField2 *)
PNIBufExpand(AlignField2, AlignField2, 64)

struct AlignField2 {
    int8_t a; /* padding */ uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8; uint8_t : 8;
    int8_t b;
    int32_t c; /* padding */ uint32_t : 32; uint32_t : 32; uint32_t : 32; uint32_t : 32; uint32_t : 32; uint32_t : 32;
};

JNIEXPORT int8_t JNICALL JavaCritical_io_vproxy_pni_test_AlignField2_aaaa(AlignField2 * self);
JNIEXPORT int8_t JNICALL JavaCritical_io_vproxy_pni_test_AlignField2_bbbb(AlignField2 * self);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_test_AlignField2_cccc(AlignField2 * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_AlignField2
// metadata.generator-version: pni test
// sha256:9239bd00b26b7b4ca18efa738db7056e9cd26959b74c23a6a74844b300e5460d
