/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_BaseClass */
#ifndef _Included_io_vproxy_pni_test_BaseClass
#define _Included_io_vproxy_pni_test_BaseClass
#ifdef __cplusplus
extern "C" {
#endif

struct BaseClass;
typedef struct BaseClass BaseClass;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(BaseClass, BaseClass *)

PNI_PACK(struct, BaseClass, {
    int8_t a;
});

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_BaseClass_aaa(PNIEnv_void * env, BaseClass * self, int8_t a);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_BaseClass
// metadata.generator-version: pni test
// sha256:07a89abc07768440a4bd795612bdc3fd4c27992d4d2941eedcda24e9c881b7e5
