/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_PrimitiveStruct */
#ifndef _Included_io_vproxy_pni_test_PrimitiveStruct
#define _Included_io_vproxy_pni_test_PrimitiveStruct
#ifdef __cplusplus
extern "C" {
#endif

struct PrimitiveStruct;
typedef struct PrimitiveStruct PrimitiveStruct;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(PrimitiveStruct, PrimitiveStruct *)
PNIBufExpand(PrimitiveStruct, PrimitiveStruct, 1000)

PNI_PACK(struct, PrimitiveStruct, {
    int8_t aByte;
    uint8_t unsignedByte;
    uint16_t aChar; /* padding */ uint32_t : 32;
    double aDouble;
    float aFloat;
    int32_t aInt;
    uint32_t unsignedInt; /* padding */ uint32_t : 32;
    int64_t aLong;
    uint64_t unsignedLong;
    int16_t aShort;
    uint16_t unsignedShort;
    uint8_t aBoolean;
    int8_t byteArray[11];
    uint8_t unsignedByteArray[12];
    uint16_t charArray[13]; /* padding */ uint16_t : 16;
    double doubleArray[14];
    float floatArray[15];
    int32_t intArray[16];
    uint32_t unsignedIntArray[17];
    int64_t longArray[18];
    uint64_t unsignedLongArray[19];
    int16_t shortArray[20];
    uint16_t unsignedShortArray[21];
    uint8_t booleanArray[22];
    PNIBuf_byte byteArrayPointer;
    PNIBuf_ubyte unsignedByteArrayPointer;
    PNIBuf_char charArrayPointer;
    PNIBuf_double doubleArrayPointer;
    PNIBuf_float floatArrayPointer;
    PNIBuf_int intArrayPointer;
    PNIBuf_uint unsignedIntArrayPointer;
    PNIBuf_long longArrayPointer;
    PNIBuf_ulong unsignedLongArrayPointer;
    PNIBuf_short shortArrayPointer;
    PNIBuf_ushort unsignedShortArrayPointer;
    PNIBuf_bool booleanArrayPointer;
});

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_func1(PNIEnv_void * env, PrimitiveStruct * self, int8_t aByte, uint8_t unsignedByte, int32_t aInt, uint32_t unsignedInt, int64_t aLong, uint64_t unsignedLong, int16_t aShort, uint16_t unsignedShort);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_func1Critical(PrimitiveStruct * self, int8_t aByte, uint8_t unsignedByte, int32_t aInt, uint32_t unsignedInt, int64_t aLong, uint64_t unsignedLong, int16_t aShort, uint16_t unsignedShort);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_func2(PNIEnv_void * env, PrimitiveStruct * self, uint16_t aChar, double aDouble, float aFloat, uint8_t aBoolean);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_func2Critical(PrimitiveStruct * self, uint16_t aChar, double aDouble, float aFloat, uint8_t aBoolean);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_func3(PNIEnv_void * env, PrimitiveStruct * self, PNIBuf_byte * byteArray, PNIBuf_ubyte * unsignedByteArray, PNIBuf_int * intArray, PNIBuf_uint * unsignedIntArray, PNIBuf_long * longArray, PNIBuf_ulong * unsignedLongArray, PNIBuf_short * shortArray, PNIBuf_ushort * unsignedShortArray);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_func3Critical(PrimitiveStruct * self, PNIBuf_byte * byteArray, PNIBuf_ubyte * unsignedByteArray, PNIBuf_int * intArray, PNIBuf_uint * unsignedIntArray, PNIBuf_long * longArray, PNIBuf_ulong * unsignedLongArray, PNIBuf_short * shortArray, PNIBuf_ushort * unsignedShortArray);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_func4(PNIEnv_void * env, PrimitiveStruct * self, PNIBuf_char * charArray, PNIBuf_double * doubleArray, PNIBuf_float * floatArray, PNIBuf_bool * booleanArray);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_func4Critical(PrimitiveStruct * self, PNIBuf_char * charArray, PNIBuf_double * doubleArray, PNIBuf_float * floatArray, PNIBuf_bool * booleanArray);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveByte(PNIEnv_byte * env, PrimitiveStruct * self);
JNIEXPORT int8_t JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveByteCritical(PrimitiveStruct * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveUnsignedByte(PNIEnv_byte * env, PrimitiveStruct * self);
JNIEXPORT int8_t JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveUnsignedByteCritical(PrimitiveStruct * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveChar(PNIEnv_char * env, PrimitiveStruct * self);
JNIEXPORT uint16_t JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveCharCritical(PrimitiveStruct * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveDouble(PNIEnv_double * env, PrimitiveStruct * self);
JNIEXPORT double JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveDoubleCritical(PrimitiveStruct * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveFloat(PNIEnv_float * env, PrimitiveStruct * self);
JNIEXPORT float JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveFloatCritical(PrimitiveStruct * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveInt(PNIEnv_int * env, PrimitiveStruct * self);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveIntCritical(PrimitiveStruct * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveUnsignedInt(PNIEnv_int * env, PrimitiveStruct * self);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveUnsignedIntCritical(PrimitiveStruct * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveLong(PNIEnv_long * env, PrimitiveStruct * self);
JNIEXPORT int64_t JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveLongCritical(PrimitiveStruct * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveUnsignedLong(PNIEnv_long * env, PrimitiveStruct * self);
JNIEXPORT int64_t JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveUnsignedLongCritical(PrimitiveStruct * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveShort(PNIEnv_short * env, PrimitiveStruct * self);
JNIEXPORT int16_t JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveShortCritical(PrimitiveStruct * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveUnsignedShort(PNIEnv_short * env, PrimitiveStruct * self);
JNIEXPORT int16_t JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveUnsignedShortCritical(PrimitiveStruct * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveBoolean(PNIEnv_bool * env, PrimitiveStruct * self);
JNIEXPORT uint8_t JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveBooleanCritical(PrimitiveStruct * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveByteArray(PNIEnv_buf_byte * env, PrimitiveStruct * self);
JNIEXPORT PNIBuf_byte * JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveByteArrayCritical(PrimitiveStruct * self, PNIBuf_byte * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveUnsignedByteArray(PNIEnv_buf_byte * env, PrimitiveStruct * self);
JNIEXPORT PNIBuf_byte * JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveUnsignedByteArrayCritical(PrimitiveStruct * self, PNIBuf_byte * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveCharArray(PNIEnv_buf_char * env, PrimitiveStruct * self);
JNIEXPORT PNIBuf_char * JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveCharArrayCritical(PrimitiveStruct * self, PNIBuf_char * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveDoubleArray(PNIEnv_buf_double * env, PrimitiveStruct * self);
JNIEXPORT PNIBuf_double * JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveDoubleArrayCritical(PrimitiveStruct * self, PNIBuf_double * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveFloatArray(PNIEnv_buf_float * env, PrimitiveStruct * self);
JNIEXPORT PNIBuf_float * JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveFloatArrayCritical(PrimitiveStruct * self, PNIBuf_float * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveIntArray(PNIEnv_buf_int * env, PrimitiveStruct * self);
JNIEXPORT PNIBuf_int * JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveIntArrayCritical(PrimitiveStruct * self, PNIBuf_int * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveUnsignedIntArray(PNIEnv_buf_int * env, PrimitiveStruct * self);
JNIEXPORT PNIBuf_int * JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveUnsignedIntArrayCritical(PrimitiveStruct * self, PNIBuf_int * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveLongArray(PNIEnv_buf_long * env, PrimitiveStruct * self);
JNIEXPORT PNIBuf_long * JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveLongArrayCritical(PrimitiveStruct * self, PNIBuf_long * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveUnsignedLongArray(PNIEnv_buf_long * env, PrimitiveStruct * self);
JNIEXPORT PNIBuf_long * JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveUnsignedLongArrayCritical(PrimitiveStruct * self, PNIBuf_long * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveShortArray(PNIEnv_buf_short * env, PrimitiveStruct * self);
JNIEXPORT PNIBuf_short * JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveShortArrayCritical(PrimitiveStruct * self, PNIBuf_short * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveUnsignedShortArray(PNIEnv_buf_short * env, PrimitiveStruct * self);
JNIEXPORT PNIBuf_short * JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveUnsignedShortArrayCritical(PrimitiveStruct * self, PNIBuf_short * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveBooleanArray(PNIEnv_buf_bool * env, PrimitiveStruct * self);
JNIEXPORT PNIBuf_bool * JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveBooleanArrayCritical(PrimitiveStruct * self, PNIBuf_bool * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveByteArrayPointer(PNIEnv_buf_byte * env, PrimitiveStruct * self);
JNIEXPORT PNIBuf_byte * JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveByteArrayPointerCritical(PrimitiveStruct * self, PNIBuf_byte * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveUnsignedByteArrayPointer(PNIEnv_buf_byte * env, PrimitiveStruct * self);
JNIEXPORT PNIBuf_byte * JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveUnsignedByteArrayPointerCritical(PrimitiveStruct * self, PNIBuf_byte * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveCharArrayPointer(PNIEnv_buf_char * env, PrimitiveStruct * self);
JNIEXPORT PNIBuf_char * JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveCharArrayPointerCritical(PrimitiveStruct * self, PNIBuf_char * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveDoubleArrayPointer(PNIEnv_buf_double * env, PrimitiveStruct * self);
JNIEXPORT PNIBuf_double * JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveDoubleArrayPointerCritical(PrimitiveStruct * self, PNIBuf_double * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveFloatArrayPointer(PNIEnv_buf_float * env, PrimitiveStruct * self);
JNIEXPORT PNIBuf_float * JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveFloatArrayPointerCritical(PrimitiveStruct * self, PNIBuf_float * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveIntArrayPointer(PNIEnv_buf_int * env, PrimitiveStruct * self);
JNIEXPORT PNIBuf_int * JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveIntArrayPointerCritical(PrimitiveStruct * self, PNIBuf_int * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveUnsignedIntArrayPointer(PNIEnv_buf_int * env, PrimitiveStruct * self);
JNIEXPORT PNIBuf_int * JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveUnsignedIntArrayPointerCritical(PrimitiveStruct * self, PNIBuf_int * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveLongArrayPointer(PNIEnv_buf_long * env, PrimitiveStruct * self);
JNIEXPORT PNIBuf_long * JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveLongArrayPointerCritical(PrimitiveStruct * self, PNIBuf_long * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveUnsignedLongArrayPointer(PNIEnv_buf_long * env, PrimitiveStruct * self);
JNIEXPORT PNIBuf_long * JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveUnsignedLongArrayPointerCritical(PrimitiveStruct * self, PNIBuf_long * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveShortArrayPointer(PNIEnv_buf_short * env, PrimitiveStruct * self);
JNIEXPORT PNIBuf_short * JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveShortArrayPointerCritical(PrimitiveStruct * self, PNIBuf_short * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveUnsignedShortArrayPointer(PNIEnv_buf_short * env, PrimitiveStruct * self);
JNIEXPORT PNIBuf_short * JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveUnsignedShortArrayPointerCritical(PrimitiveStruct * self, PNIBuf_short * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_retrieveBooleanArrayPointer(PNIEnv_buf_bool * env, PrimitiveStruct * self);
JNIEXPORT PNIBuf_bool * JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_retrieveBooleanArrayPointerCritical(PrimitiveStruct * self, PNIBuf_bool * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_checkPointerSetToNonNull(PNIEnv_bool * env, PrimitiveStruct * self);
JNIEXPORT uint8_t JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_checkPointerSetToNonNullCritical(PrimitiveStruct * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PrimitiveStruct_checkPointerSetToNull(PNIEnv_bool * env, PrimitiveStruct * self);
JNIEXPORT uint8_t JNICALL JavaCritical_io_vproxy_pni_test_PrimitiveStruct_checkPointerSetToNullCritical(PrimitiveStruct * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_PrimitiveStruct
// metadata.generator-version: pni test
// sha256:91a2938e44090e0724edf9e2ef77a348e79dd83c81ee4d32af12b03ed511fbe2
