/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_AlwaysAlignedSizeof */
#ifndef _Included_io_vproxy_pni_test_AlwaysAlignedSizeof
#define _Included_io_vproxy_pni_test_AlwaysAlignedSizeof
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "sizeof.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(SizeofStructExpr, SizeofStructExpr *)

JNIEXPORT size_t JNICALL JavaCritical_io_vproxy_pni_test_AlwaysAlignedSizeof___getLayoutByteSize();

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_AlwaysAlignedSizeof
// metadata.generator-version: pni test
// sha256:a240efe184336c06cc617fb97ee42f357d5890917b9c5fc279bdeb6b7b3b7b0f
