/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_PackedBaseClass */
#ifndef _Included_io_vproxy_pni_test_PackedBaseClass
#define _Included_io_vproxy_pni_test_PackedBaseClass
#ifdef __cplusplus
extern "C" {
#endif

struct PackedBaseClass;
typedef struct PackedBaseClass PackedBaseClass;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(PackedBaseClass, PackedBaseClass *)
PNIBufExpand(PackedBaseClass, PackedBaseClass, 3)

PNI_PACK(struct, PackedBaseClass, {
    int8_t a;
    int16_t b;
});

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PackedBaseClass_aaa(PNIEnv_void * env, PackedBaseClass * self, int8_t a);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PackedBaseClass_bbb(PNIEnv_void * env, PackedBaseClass * self, int16_t b);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_PackedBaseClass
// metadata.generator-version: pni test
// sha256:5d83e77ea207d79aa91f82ff2c84b919344730c13168127cd599d297f80c793c
