/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_PointerOnlyStruct */
#ifndef _Included_io_vproxy_pni_test_PointerOnlyStruct
#define _Included_io_vproxy_pni_test_PointerOnlyStruct
#ifdef __cplusplus
extern "C" {
#endif

struct PointerOnlyStruct;
typedef struct PointerOnlyStruct PointerOnlyStruct;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(PointerOnlyStruct, PointerOnlyStruct *)
PNIBufExpand(PointerOnlyStruct, PointerOnlyStruct, (0 /* !!invalid!! */))

JNIEXPORT int64_t JNICALL JavaCritical_io_vproxy_pni_test_PointerOnlyStruct_retrieve(PointerOnlyStruct * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_PointerOnlyStruct
// metadata.generator-version: pni test
// sha256:f8cfe7cc7a0cd5b1b2e608b8cfd0dfd6459c0033728bb2cad72b4a6dd7c1fa80
