/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCCompatibilityPackedContainNonPacked */
#ifndef _Included_io_vproxy_pni_test_GCCCompatibilityPackedContainNonPacked
#define _Included_io_vproxy_pni_test_GCCCompatibilityPackedContainNonPacked
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "gcc_compatibility.h"
#include "io_vproxy_pni_test_GCCCompatibilityNormal.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityPackedContainNonPacked_init(PNIEnv_void * env, GCCCompatibilityPackedContainNonPacked * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityPackedContainNonPacked_size(PNIEnv_long * env, GCCCompatibilityPackedContainNonPacked * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCCompatibilityPackedContainNonPacked
// sha256:99ffaba46f022f24c2ef135ccea724afd83f2c70ac9be90de73b37f97688c2d8
