/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_AlwaysAlignedField */
#ifndef _Included_io_vproxy_pni_test_AlwaysAlignedField
#define _Included_io_vproxy_pni_test_AlwaysAlignedField
#ifdef __cplusplus
extern "C" {
#endif

struct AlwaysAlignedField;
typedef struct AlwaysAlignedField AlwaysAlignedField;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(AlwaysAlignedField, AlwaysAlignedField *)

PNI_PACK(struct, AlwaysAlignedField, {
    int8_t a;
    int16_t b;
    int8_t c;
    int32_t d;
    int64_t e;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_AlwaysAlignedField
// metadata.generator-version: pni test
// sha256:f1de4ccbb3f4357aedc22f96f10dbbab57019f15ae8a3244dc494ffd33d811f0
