/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_StructN */
#ifndef _Included_io_vproxy_pni_test_StructN
#define _Included_io_vproxy_pni_test_StructN
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_StructUnionAnnotation.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_StructN_retrieveS(PNIEnv_short * env, struct N_st * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_StructN_retrieveL(PNIEnv_long * env, struct N_st * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_StructN
// sha256:ea5b1adfba3c09acd816652a641d522349fa04ee149ae6cbe5e9294199b2763d
