/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCCompatibilityUnion */
#ifndef _Included_io_vproxy_pni_test_GCCCompatibilityUnion
#define _Included_io_vproxy_pni_test_GCCCompatibilityUnion
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCCompatibilityUnion
// sha256:e88d2d2a7bcc1903c6d18eb88360f9ca3b208f0ef4be4d37c3bd36f28ead0695
