/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_SizeofUnion */
#ifndef _Included_io_vproxy_pni_test_SizeofUnion
#define _Included_io_vproxy_pni_test_SizeofUnion
#ifdef __cplusplus
extern "C" {
#endif

union SizeofUnion;
typedef union SizeofUnion SizeofUnion;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_SizeofStruct.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(SizeofUnion, SizeofUnion *)

PNI_PACK(union, SizeofUnion, {
    SizeofStruct st;
    int32_t a;
});

JNIEXPORT size_t JNICALL JavaCritical_io_vproxy_pni_test_SizeofUnion___getLayoutByteSize();

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_SizeofUnion
// metadata.generator-version: pni test
// sha256:42c0a3844c82e5270fcfb11f32c3fd2082be680938be2fab5c4176e67aeb94c4
