/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_SizeofStructExpr */
#ifndef _Included_io_vproxy_pni_test_SizeofStructExpr
#define _Included_io_vproxy_pni_test_SizeofStructExpr
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "sizeof.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(SizeofStructExpr, SizeofStructExpr *)

JNIEXPORT size_t JNICALL JavaCritical_io_vproxy_pni_test_SizeofStructExpr___getLayoutByteSize();

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_SizeofStructExpr
// metadata.generator-version: pni test
// sha256:82b09f50f820ad9b5303bbd4227934eb9601a9642589ce15c6f5abfba8fcaa78
