/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_Userdata */
#ifndef _Included_io_vproxy_pni_test_Userdata
#define _Included_io_vproxy_pni_test_Userdata
#ifdef __cplusplus
extern "C" {
#endif

struct Userdata;
typedef struct Userdata Userdata;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(Userdata, Userdata *)
PNIBufExpand(Userdata, Userdata, 24)

PNI_PACK(struct, Userdata, {
    int32_t x; /* padding */ uint64_t :32;
    int64_t y;
    int16_t z; /* padding */ uint64_t :48;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_Userdata
// metadata.generator-version: pni test
// sha256:0368ca83503d55a8335eb2eab5b1747d99f4bb887303ca7772662f3a974febd7
