/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_KtStruct */
#ifndef _Included_io_vproxy_pni_test_KtStruct
#define _Included_io_vproxy_pni_test_KtStruct
#ifdef __cplusplus
extern "C" {
#endif

struct KtStruct;
typedef struct KtStruct KtStruct;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(KtStruct, KtStruct *)
PNIBufExpand(KtStruct, KtStruct, 16)

struct KtStruct {
    int32_t aInt;
    int64_t aLong;
};

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_KtStruct_retrieveInt(PNIEnv_int * env, KtStruct * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_KtStruct_retrieveLong(PNIEnv_long * env, KtStruct * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_KtStruct
// metadata.generator-version: pni test
// sha256:9a7a8c9c3fe953e8ae66b59b74e22b436cdfc24f325459ff07365d87b9ea3693
