/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_ChildOfLargeAlign */
#ifndef _Included_io_vproxy_pni_test_ChildOfLargeAlign
#define _Included_io_vproxy_pni_test_ChildOfLargeAlign
#ifdef __cplusplus
extern "C" {
#endif

struct ChildOfLargeAlign;
typedef struct ChildOfLargeAlign ChildOfLargeAlign;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_LargeAlignBase.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(ChildOfLargeAlign, ChildOfLargeAlign *)
PNIBufExpand(ChildOfLargeAlign, ChildOfLargeAlign, 16)

PNI_PACK(struct, ChildOfLargeAlign, {
    LargeAlignBase SUPER;
    int8_t y; /* padding */ uint32_t : 32; uint16_t : 16; uint8_t : 8;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_ChildOfLargeAlign
// metadata.generator-version: pni test
// sha256:29c14a579157dc664f2f2056c1191af6c87f03eaf477891ea779a6249054b00d
