/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_ChildOfLargeAlign */
#ifndef _Included_io_vproxy_pni_test_ChildOfLargeAlign
#define _Included_io_vproxy_pni_test_ChildOfLargeAlign
#ifdef __cplusplus
extern "C" {
#endif

struct ChildOfLargeAlign;
typedef struct ChildOfLargeAlign ChildOfLargeAlign;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_LargeAlignBase.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(ChildOfLargeAlign, ChildOfLargeAlign *)

PNI_PACK(struct, ChildOfLargeAlign, {
    LargeAlignBase SUPER;
    int8_t y; /* padding */ uint64_t :56;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_ChildOfLargeAlign
// metadata.generator-version: pni test
// sha256:9176472ed8265d53888631a48de77353d43f2a4ef173f28ef582bf168c084fdf
