/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_CustomNativeTypeStruct */
#ifndef _Included_io_vproxy_pni_test_CustomNativeTypeStruct
#define _Included_io_vproxy_pni_test_CustomNativeTypeStruct
#ifdef __cplusplus
extern "C" {
#endif

struct CustomNativeTypeStruct;
typedef struct CustomNativeTypeStruct CustomNativeTypeStruct;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "sizeof.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(CustomNativeTypeStruct, CustomNativeTypeStruct *)
PNIBufExpand(CustomNativeTypeStruct, CustomNativeTypeStruct, 8)

struct CustomNativeTypeStruct {
    SizeofStructExpr* field;
};

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_CustomNativeTypeStruct_getP1(PNIEnv_long * env, CustomNativeTypeStruct * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_CustomNativeTypeStruct
// metadata.generator-version: pni test
// sha256:cc504dec2ca3f225d5f30b87125415d60de8bc3535b44afd9d948d344341a24f
