/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_CustomNativeTypeFunc */
#ifndef _Included_io_vproxy_pni_test_CustomNativeTypeFunc
#define _Included_io_vproxy_pni_test_CustomNativeTypeFunc
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "sizeof.h"
#include "io_vproxy_pni_test_CustomNativeTypeUpcall.h"
#include "io_vproxy_pni_test_SizeofStructExpr.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int64_t* JNICALL JavaCritical_io_vproxy_pni_test_CustomNativeTypeFunc_exec(SizeofStructExpr* o);
JNIEXPORT int64_t* JNICALL JavaCritical_io_vproxy_pni_test_CustomNativeTypeFunc_invoke(SizeofStructExpr * s);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_CustomNativeTypeFunc
// metadata.generator-version: pni test
// sha256:cf533886453fd7b44b3071156f30e61145bd57a68e1e8668d90396b494d1d567
