/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_AlignField */
#ifndef _Included_io_vproxy_pni_test_AlignField
#define _Included_io_vproxy_pni_test_AlignField
#ifdef __cplusplus
extern "C" {
#endif

struct AlignField;
typedef struct AlignField AlignField;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(AlignField, AlignField *)
PNIBufExpand(AlignField, AlignField, 8)

struct AlignField {
    int8_t a; /* padding */ uint8_t : 8;
    int8_t b;
    int32_t c;
};

JNIEXPORT int8_t JNICALL JavaCritical_io_vproxy_pni_test_AlignField_aaaa(AlignField * self);
JNIEXPORT int8_t JNICALL JavaCritical_io_vproxy_pni_test_AlignField_bbbb(AlignField * self);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_test_AlignField_cccc(AlignField * self);
JNIEXPORT int64_t JNICALL JavaCritical_io_vproxy_pni_test_AlignField_size(AlignField * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_AlignField
// metadata.generator-version: pni test
// sha256:8684fed13909835e5b30c51b581d33cd81d8b7b7211c6563a14ddae08e252094
