/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_PointerArrayField */
#ifndef _Included_io_vproxy_pni_test_PointerArrayField
#define _Included_io_vproxy_pni_test_PointerArrayField
#ifdef __cplusplus
extern "C" {
#endif

struct PointerArrayField;
typedef struct PointerArrayField PointerArrayField;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(PointerArrayField, PointerArrayField *)
PNIBufExpand(PointerArrayField, PointerArrayField, 40)

struct PointerArrayField {
    void * pointerArray[3];
    PNIBuf_ptr pointerArrayPointer;
};

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PointerArrayField_set(PNIEnv_void * env, PointerArrayField * self, PNIBuf_ptr * a);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PointerArrayField_getPtrField(PNIEnv_buf_ptr * env, PointerArrayField * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_PointerArrayField_getLenField(PNIEnv_buf_ptr * env, PointerArrayField * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_PointerArrayField
// metadata.generator-version: pni test
// sha256:93b9de21f221dcdf8248bf4559e440c9cba43d33ae6ba8c44c4f7e1e6dc7de76
