/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_ToStringArray */
#ifndef _Included_io_vproxy_pni_test_ToStringArray
#define _Included_io_vproxy_pni_test_ToStringArray
#ifdef __cplusplus
extern "C" {
#endif

struct ToStringArray;
typedef struct ToStringArray ToStringArray;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(ToStringArray, ToStringArray *)
PNIBufExpand(ToStringArray, ToStringArray, 64)

struct ToStringArray {
    ToStringClass arrc[0];
    ToStringClass arrcLen2[2];
    PNIBuf_ToStringClass parrc;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_ToStringArray
// metadata.generator-version: pni test
// sha256:88bb51f496b828dd5015a310cb04de384890fc6b852288fa9cddaed3f5acda82
