/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCCompatibilityArrayZero */
#ifndef _Included_io_vproxy_pni_test_GCCCompatibilityArrayZero
#define _Included_io_vproxy_pni_test_GCCCompatibilityArrayZero
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "gcc_compatibility.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityArrayZero_init(PNIEnv_void * env, GCCCompatibilityArrayZero * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityArrayZero_size(PNIEnv_long * env, GCCCompatibilityArrayZero * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCCompatibilityArrayZero
// sha256:b0cd362ce82f999bc0fec191d74480610f2454368b04bce19bf822ca5c4410b5
