/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_NoAlloc */
#ifndef _Included_io_vproxy_pni_test_NoAlloc
#define _Included_io_vproxy_pni_test_NoAlloc
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_ObjectStruct.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_NoAlloc_execNoAlloc(PNIEnv_ObjectStruct * env);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_NoAlloc_invokeUpcall(PNIEnv_ObjectStruct * env);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_NoAlloc
// metadata.generator-version: pni test
// sha256:575fd5c31777eadf05cf878b6d96b202eca50c46f7e5d682e907841833abf4e2
