/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_StructM */
#ifndef _Included_io_vproxy_pni_test_StructM
#define _Included_io_vproxy_pni_test_StructM
#ifdef __cplusplus
extern "C" {
#endif

struct StructM;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_StructN.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(StructM, struct StructM *)

PNI_PACK(struct, StructM, {
    struct N_st n_st;
});

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_StructM_nnn(PNIEnv_void * env, struct StructM * self, struct N_st * n_st);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_StructM
// sha256:dcd1313a2eea604d3ac338770d30a9b6f840fa5a218f9bfdfaed69035b9a49e2
