/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_AlwaysAlignedBase */
#ifndef _Included_io_vproxy_pni_test_AlwaysAlignedBase
#define _Included_io_vproxy_pni_test_AlwaysAlignedBase
#ifdef __cplusplus
extern "C" {
#endif

struct AlwaysAlignedBase;
typedef struct AlwaysAlignedBase AlwaysAlignedBase;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(AlwaysAlignedBase, AlwaysAlignedBase *)
PNIBufExpand(AlwaysAlignedBase, AlwaysAlignedBase, 1)

struct AlwaysAlignedBase {
    int8_t a;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_AlwaysAlignedBase
// metadata.generator-version: pni test
// sha256:b7f7dce8ce4c52d9b718a5d9b69aa7dc0e46daf34ed053585bc785110ec56bdc
