/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_StructD */
#ifndef _Included_io_vproxy_pni_test_StructD
#define _Included_io_vproxy_pni_test_StructD
#ifdef __cplusplus
extern "C" {
#endif

struct StructD;
typedef struct StructD StructD;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(StructD, StructD *)
PNIBufExpand(StructD, StructD, 16)

struct StructD {
    int32_t n;
    double d;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_StructD
// metadata.generator-version: pni test
// sha256:4dfdb06fa36b10f2e8ec963cb2172adbb1d1ec1f42334ddc6ae0e94f45d9c5f4
