/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCompatibilityPackedContainUnion */
#ifndef _Included_io_vproxy_pni_test_GCCompatibilityPackedContainUnion
#define _Included_io_vproxy_pni_test_GCCompatibilityPackedContainUnion
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "gcc_compatibility.h"
#include "io_vproxy_pni_test_GCCCompatibilityUnion.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(GCCompatibilityPackedContainUnion, GCCompatibilityPackedContainUnion *)

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCompatibilityPackedContainUnion_initB(PNIEnv_void * env, GCCompatibilityPackedContainUnion * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCompatibilityPackedContainUnion_initS(PNIEnv_void * env, GCCompatibilityPackedContainUnion * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCompatibilityPackedContainUnion_initN(PNIEnv_void * env, GCCompatibilityPackedContainUnion * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCompatibilityPackedContainUnion_initF(PNIEnv_void * env, GCCompatibilityPackedContainUnion * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCompatibilityPackedContainUnion_initD(PNIEnv_void * env, GCCompatibilityPackedContainUnion * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCompatibilityPackedContainUnion_initL(PNIEnv_void * env, GCCompatibilityPackedContainUnion * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCompatibilityPackedContainUnion_size(PNIEnv_long * env, GCCompatibilityPackedContainUnion * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCompatibilityPackedContainUnion
// sha256:18d7789885643b471f7e86a3e659786cb516df967978a201727b3259920a142d
