/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_SizeofEmbed */
#ifndef _Included_io_vproxy_pni_test_SizeofEmbed
#define _Included_io_vproxy_pni_test_SizeofEmbed
#ifdef __cplusplus
extern "C" {
#endif

struct SizeofEmbed;
typedef struct SizeofEmbed SizeofEmbed;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_SizeofUnion.h"
#include "io_vproxy_pni_test_SizeofStructExpr.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT size_t JNICALL JavaCritical_io_vproxy_pni_test_SizeofEmbed___getLayoutByteSize();

PNIEnvExpand(SizeofEmbed, SizeofEmbed *)
PNIBufExpand(SizeofEmbed, SizeofEmbed, JavaCritical_io_vproxy_pni_test_SizeofEmbed___getLayoutByteSize())

PNI_PACK(struct, SizeofEmbed, {
    int8_t x; /* padding */ uint64_t :56;
    SizeofUnion * un;
    SizeofStructExpr st;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_SizeofEmbed
// metadata.generator-version: pni test
// sha256:db468c7200b825da7e2b497db288543d92b775f72a1ff551fd78ff831a51b0ff
