/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_UnionEmbedded */
#ifndef _Included_io_vproxy_pni_test_UnionEmbedded
#define _Included_io_vproxy_pni_test_UnionEmbedded
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_UnionEmbedded
// metadata.generator-version: pni test
// sha256:f775a97a09212a249e2877d2867b916518f1073766f15a7ff9458b3588c1eeaf
