/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCCompatibilityPackedContainNonPacked */
#ifndef _Included_io_vproxy_pni_test_GCCCompatibilityPackedContainNonPacked
#define _Included_io_vproxy_pni_test_GCCCompatibilityPackedContainNonPacked
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "gcc_compatibility.h"
#include "io_vproxy_pni_test_GCCCompatibilityNormal.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(GCCCompatibilityPackedContainNonPacked, GCCCompatibilityPackedContainNonPacked *)
PNIBufExpand(GCCCompatibilityPackedContainNonPacked, GCCCompatibilityPackedContainNonPacked, 37)

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityPackedContainNonPacked_init(PNIEnv_void * env, GCCCompatibilityPackedContainNonPacked * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityPackedContainNonPacked_size(PNIEnv_long * env, GCCCompatibilityPackedContainNonPacked * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCCompatibilityPackedContainNonPacked
// metadata.generator-version: pni test
// sha256:91847d5c2d09d368e95a79eb3c9cbd43b21927c8c634eb893e1934a91f056c71
