/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_AlwaysAlignedUnion */
#ifndef _Included_io_vproxy_pni_test_AlwaysAlignedUnion
#define _Included_io_vproxy_pni_test_AlwaysAlignedUnion
#ifdef __cplusplus
extern "C" {
#endif

union AlwaysAlignedUnion;
typedef union AlwaysAlignedUnion AlwaysAlignedUnion;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(AlwaysAlignedUnion, AlwaysAlignedUnion *)
PNIBufExpand(AlwaysAlignedUnion, AlwaysAlignedUnion, 8)

union AlwaysAlignedUnion {
    int16_t a;
    int32_t b;
    int64_t c;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_AlwaysAlignedUnion
// metadata.generator-version: pni test
// sha256:fff030a231ff9089167f2af94a29aafe2ca48c457d2c2a7b1fdcf523c825244c
