/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_NativeCheck */
#ifndef _Included_io_vproxy_pni_test_NativeCheck
#define _Included_io_vproxy_pni_test_NativeCheck
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_Userdata.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_NativeCheck_checkUserdataForRef(PNIEnv_void * env, PNIRef * ref, int32_t * x, int64_t * y, int16_t * z);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_NativeCheck_checkUserdataForFunc(PNIEnv_void * env, PNIFunc * func, int32_t * x, int64_t * y, int16_t * z);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_NativeCheck
// metadata.generator-version: pni test
// sha256:3c5b86a91c0eb5288c1964ad484aab0cffd8b79dc74a6974fded3d9420e70722
