/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_Userdata */
#ifndef _Included_io_vproxy_pni_test_Userdata
#define _Included_io_vproxy_pni_test_Userdata
#ifdef __cplusplus
extern "C" {
#endif

struct Userdata;
typedef struct Userdata Userdata;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(Userdata, Userdata *)
PNIBufExpand(Userdata, Userdata, 24)

PNI_PACK(struct, Userdata, {
    int32_t x; /* padding */ uint32_t : 32;
    int64_t y;
    int16_t z; /* padding */ uint32_t : 32; uint16_t : 16;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_Userdata
// metadata.generator-version: pni test
// sha256:45cc2866b912b62406838305e805176402d9d6f9e6b5c81e757f39357dfd604f
