/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_Func */
#ifndef _Included_io_vproxy_pni_test_Func
#define _Included_io_vproxy_pni_test_Func
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_ObjectStruct.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Func_func1(PNIEnv_int * env);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_test_Func_func1Critical(void);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Func_func2(PNIEnv_void * env);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Func_func3(PNIEnv_void * env, char * ex);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Func_write(PNIEnv_int * env, int32_t fd, void * buf, int32_t off, int32_t len);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_test_Func_writeCritical(int32_t fd, void * buf, int32_t off, int32_t len);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Func_writeWithErrno(PNIEnv_int * env, int32_t fd, void * buf, int32_t off, int32_t len);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Func_writeByteArray(PNIEnv_int * env, int32_t fd, void * buf, int32_t off, int32_t len);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Func_callJavaFromC(PNIEnv_pointer * env, PNIFunc * func);
JNIEXPORT void * JNICALL JavaCritical_io_vproxy_pni_test_Func_callJavaFromCCritical(PNIFunc * func);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Func_callJavaRefFromC(PNIEnv_void * env, PNIFunc * func, PNIRef * ref);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_pni_test_Func_callJavaRefFromCCritical(PNIFunc * func, PNIRef * ref);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Func_callJavaMethodWithRefFromC(PNIEnv_int * env, void * func, PNIRef * ref, int32_t a);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_test_Func_callJavaMethodWithRefFromCCritical(void * func, PNIRef * ref, int32_t a);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_Func
// metadata.generator-version: pni test
// sha256:f4f9f3d8219c25b41a342def73abcc00801691b089723c3cdf2ab264e1e0e448
