/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCompatibilityBitField */
#ifndef _Included_io_vproxy_pni_test_GCCompatibilityBitField
#define _Included_io_vproxy_pni_test_GCCompatibilityBitField
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "gcc_compatibility.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(GCCompatibilityBitField, GCCompatibilityBitField *)

JNIEXPORT void JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_set(GCCompatibilityBitField * self, uint8_t a, uint8_t a2, uint8_t b, uint8_t b2, uint16_t c, uint16_t c2, uint16_t d, uint16_t d2, uint16_t e, uint16_t e2, uint32_t f, uint32_t f2, uint32_t g, uint32_t g2, uint32_t h, uint32_t h2, uint32_t i, uint32_t i2, uint64_t j, uint64_t j2, uint64_t k, uint64_t k2, uint64_t l, uint64_t l2, uint64_t m, uint64_t m2);
JNIEXPORT int8_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_a(GCCompatibilityBitField * self);
JNIEXPORT int8_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_a2(GCCompatibilityBitField * self);
JNIEXPORT int8_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_b(GCCompatibilityBitField * self);
JNIEXPORT int8_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_b2(GCCompatibilityBitField * self);
JNIEXPORT int16_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_c(GCCompatibilityBitField * self);
JNIEXPORT int16_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_c2(GCCompatibilityBitField * self);
JNIEXPORT int16_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_d(GCCompatibilityBitField * self);
JNIEXPORT int16_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_d2(GCCompatibilityBitField * self);
JNIEXPORT int16_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_e(GCCompatibilityBitField * self);
JNIEXPORT int16_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_e2(GCCompatibilityBitField * self);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_f(GCCompatibilityBitField * self);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_f2(GCCompatibilityBitField * self);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_g(GCCompatibilityBitField * self);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_g2(GCCompatibilityBitField * self);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_h(GCCompatibilityBitField * self);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_h2(GCCompatibilityBitField * self);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_i(GCCompatibilityBitField * self);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_i2(GCCompatibilityBitField * self);
JNIEXPORT int64_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_j(GCCompatibilityBitField * self);
JNIEXPORT int64_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_j2(GCCompatibilityBitField * self);
JNIEXPORT int64_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_k(GCCompatibilityBitField * self);
JNIEXPORT int64_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_k2(GCCompatibilityBitField * self);
JNIEXPORT int64_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_l(GCCompatibilityBitField * self);
JNIEXPORT int64_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_l2(GCCompatibilityBitField * self);
JNIEXPORT int64_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_m(GCCompatibilityBitField * self);
JNIEXPORT int64_t JNICALL JavaCritical_io_vproxy_pni_test_GCCompatibilityBitField_m2(GCCompatibilityBitField * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCompatibilityBitField
// metadata.generator-version: pni test
// sha256:e0721ccff37e39741fbd6ed5e56823ad885fff912a3a566345d181cde6da0dcd
