/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_AlwaysAlignedBase */
#ifndef _Included_io_vproxy_pni_test_AlwaysAlignedBase
#define _Included_io_vproxy_pni_test_AlwaysAlignedBase
#ifdef __cplusplus
extern "C" {
#endif

struct AlwaysAlignedBase;
typedef struct AlwaysAlignedBase AlwaysAlignedBase;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(AlwaysAlignedBase, AlwaysAlignedBase *)
PNIBufExpand(AlwaysAlignedBase, AlwaysAlignedBase, 1)

PNI_PACK(struct, AlwaysAlignedBase, {
    int8_t a;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_AlwaysAlignedBase
// metadata.generator-version: pni test
// sha256:eeeb7d5928a45d02db7f6ec3c97a4bf6f620fcfb4dc8a95243e934fa03ffc21c
