/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_UnionC */
#ifndef _Included_io_vproxy_pni_test_UnionC
#define _Included_io_vproxy_pni_test_UnionC
#ifdef __cplusplus
extern "C" {
#endif

union UnionC;
typedef union UnionC UnionC;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNI_PACK(union, UnionC, {
    int32_t n;
    int64_t l;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_UnionC
// sha256:daacd9155cb56d5356447139013a7606aa0c5a64e01e87fb22d3f774e5ce77b9
