/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_Empty */
#ifndef _Included_io_vproxy_pni_test_Empty
#define _Included_io_vproxy_pni_test_Empty
#ifdef __cplusplus
extern "C" {
#endif

struct Empty;
typedef struct Empty Empty;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(Empty, Empty *)
PNIBufExpand(Empty, Empty, (0 /* !!invalid!! */))

PNI_PACK(struct, Empty, {
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_Empty
// metadata.generator-version: pni test
// sha256:e9d23b771b608280172eb264ea8be4e6b4d96ca3354cf863fb661b799129371b
