/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_ToStringClass */
#ifndef _Included_io_vproxy_pni_test_ToStringClass
#define _Included_io_vproxy_pni_test_ToStringClass
#ifdef __cplusplus
extern "C" {
#endif

struct ToStringClass;
typedef struct ToStringClass ToStringClass;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_ToStringClassRecurse.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(ToStringClass, ToStringClass *)
PNIBufExpand(ToStringClass, ToStringClass, 24)

struct ToStringClass {
    int64_t num;
    ToStringClassRecurse cr;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_ToStringClass
// metadata.generator-version: pni test
// sha256:a315f50bd8e766068e182211e338d28dab9d2f63975745e80f3e7bb83e764028
