/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCCompatibilityPackedArray */
#ifndef _Included_io_vproxy_pni_test_GCCCompatibilityPackedArray
#define _Included_io_vproxy_pni_test_GCCCompatibilityPackedArray
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "gcc_compatibility.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(GCCCompatibilityPackedArray, GCCCompatibilityPackedArray *)

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityPackedArray_init(PNIEnv_void * env, GCCCompatibilityPackedArray * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityPackedArray_size(PNIEnv_long * env, GCCCompatibilityPackedArray * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCCompatibilityPackedArray
// sha256:d6d252888ec709604a114608ac7d504a12ec356068bff385addf35942cbad6bf
