/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCCompatibilityNonPackedContainPacked */
#ifndef _Included_io_vproxy_pni_test_GCCCompatibilityNonPackedContainPacked
#define _Included_io_vproxy_pni_test_GCCCompatibilityNonPackedContainPacked
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "gcc_compatibility.h"
#include "io_vproxy_pni_test_GCCCompatibilityPacked.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(GCCCompatibilityNonPackedContainPacked, GCCCompatibilityNonPackedContainPacked *)

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityNonPackedContainPacked_init(PNIEnv_void * env, GCCCompatibilityNonPackedContainPacked * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityNonPackedContainPacked_size(PNIEnv_long * env, GCCCompatibilityNonPackedContainPacked * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCCompatibilityNonPackedContainPacked
// metadata.generator-version: pni test
// sha256:25aac47083a93e2dcbcc30b01ab66eb8a736a698bd1d6b54089609894565a75b
