/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_UnionP */
#ifndef _Included_io_vproxy_pni_test_UnionP
#define _Included_io_vproxy_pni_test_UnionP
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_StructUnionAnnotation.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(UnionP, UnionP *)
PNIBufExpand(UnionP, UnionP, 8)

JNIEXPORT int JNICALL UnionP_retrieve_i(PNIEnv_int * env, UnionP * self);
JNIEXPORT int JNICALL UnionP_retrieve_l(PNIEnv_long * env, UnionP * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_UnionP
// metadata.generator-version: pni test
// sha256:be213ab6409b21777960762d0f954d96ce94541fe877f67bd3f4daa0d8ed5aeb
