/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_AllowHeapAccess */
#ifndef _Included_io_vproxy_pni_test_AllowHeapAccess
#define _Included_io_vproxy_pni_test_AllowHeapAccess
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_AllowHeapAccess_intValue(PNIEnv_int * env, void * mem);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_test_AllowHeapAccess_intValueCritical(void * mem);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_AllowHeapAccess
// metadata.generator-version: pni test
// sha256:567c0475ebad9f14ba92304509e344b6c891a2484f050dd8eeddf17f1f2b197e
