/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_graal_test_Invoke */
#ifndef _Included_io_vproxy_pni_graal_test_Invoke
#define _Included_io_vproxy_pni_graal_test_Invoke
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_graal_test_Invoke_invokeSum(void * func, void * thread, int32_t a, int32_t b);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_pni_graal_test_Invoke_invokePtr(void * func, void * thread, int32_t a, void * p);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_pni_graal_test_Invoke_releaseRef(PNIRef * ref);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_graal_test_Invoke_callFunc(PNIFunc * func);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_pni_graal_test_Invoke_invokeDoNothingUpcall(void * func);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_graal_test_Invoke_invokeIntUpcall(void * func, int32_t a);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_graal_test_Invoke_invokeRefUpcall(void * func, PNIRef * ref);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_graal_test_Invoke_invokeFuncUpcall(void * func, PNIFunc * ff);
JNIEXPORT void * JNICALL JavaCritical_io_vproxy_pni_graal_test_Invoke_invokeReturnSegUpcall(void * func);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_graal_test_Invoke
// metadata.generator-version: pni test
// sha256:178a384903221bc51895b8062f188cb5ad3a81a406dccb2a154f02f169cee6e6
