/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_graal_test_Invoke */
#ifndef _Included_io_vproxy_pni_graal_test_Invoke
#define _Included_io_vproxy_pni_graal_test_Invoke
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_graal_test_Invoke_invokeSum(void * func, void * thread, int32_t a, int32_t b);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_pni_graal_test_Invoke_invokePtr(void * func, void * thread, int32_t a, void * p);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_graal_test_Invoke
// metadata.generator-version: pni test
// sha256:29239d0677a13662ab76eae20aaab36898dc586246db63abdd166e430e32ce25
