/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_graal_test_Upcall */
#ifndef _Included_io_vproxy_pni_graal_test_Upcall
#define _Included_io_vproxy_pni_graal_test_Upcall
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL JavaCritical_io_vproxy_pni_graal_test_Upcall_doNothingUpcall(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_graal_test_Upcall_intUpcall(int32_t a);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_graal_test_Upcall_refUpcall(PNIRef * ref);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_graal_test_Upcall_funcUpcall(PNIFunc * func);
JNIEXPORT void * JNICALL JavaCritical_io_vproxy_pni_graal_test_Upcall_returnSegUpcall(void);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_graal_test_Upcall
// metadata.generator-version: pni test
// sha256:0f6d5190d544d8d2e059764efa36695232a7fa18992346b0a7a26a168231ede8
