/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_KtUpcall */
#ifndef _Included_io_vproxy_pni_test_KtUpcall
#define _Included_io_vproxy_pni_test_KtUpcall
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_KtStruct.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT KtStruct * JNICALL JavaCritical_io_vproxy_pni_test_KtUpcall_helloworld(int32_t i, int64_t l, KtStruct * return_);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_KtUpcall
// metadata.generator-version: pni test
// sha256:f4d5fc02c0eb8e3a7c72d2fe53b2e5dd25897011efc3103ed97c854e40b4c818
