/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_DefiningCFunction */
#ifndef _Included_io_vproxy_pni_test_DefiningCFunction
#define _Included_io_vproxy_pni_test_DefiningCFunction
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_DefiningCFunction_upcallVoidNoParam(PNIEnv_void * env, void * func);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_DefiningCFunction_upcallVoid1Param(PNIEnv_void * env, void * func, void * data);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_DefiningCFunction_upcallVoid2Param(PNIEnv_void * env, void * func, void * data, int8_t b);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_DefiningCFunction_upcallVoid3Param(PNIEnv_void * env, void * func, void * data, uint8_t z, uint16_t c);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_DefiningCFunction_upcallVoid4Param(PNIEnv_void * env, void * func, void * data, double d, float f, int32_t i);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_DefiningCFunction_upcallVoid3Param2(PNIEnv_void * env, void * func, void * data, int64_t l, int16_t s);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_DefiningCFunction_upcallReturnByteNoParam(PNIEnv_byte * env, void * func);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_DefiningCFunction_upcallReturnBoolNoParam(PNIEnv_bool * env, void * func);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_DefiningCFunction_upcallReturnCharNoParam(PNIEnv_char * env, void * func);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_DefiningCFunction_upcallReturnDoubleNoParam(PNIEnv_double * env, void * func);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_DefiningCFunction_upcallReturnFloatNoParam(PNIEnv_float * env, void * func);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_DefiningCFunction_upcallReturnIntNoParam(PNIEnv_int * env, void * func);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_DefiningCFunction_upcallReturnLongNoParam(PNIEnv_long * env, void * func);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_DefiningCFunction_upcallReturnShortNoParam(PNIEnv_short * env, void * func);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_DefiningCFunction_upcallReturnPointerNoParam(PNIEnv_pointer * env, void * func);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_DefiningCFunction_upcallReturnByte1Param(PNIEnv_byte * env, void * func, int8_t b);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_DefiningCFunction_upcallReturnBool1Param(PNIEnv_bool * env, void * func, uint8_t z);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_DefiningCFunction_upcallReturnChar1Param(PNIEnv_char * env, void * func, uint16_t c);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_DefiningCFunction_upcallReturnDouble1Param(PNIEnv_double * env, void * func, double d);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_DefiningCFunction_upcallReturnFloat1Param(PNIEnv_float * env, void * func, float f);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_DefiningCFunction_upcallReturnInt1Param(PNIEnv_int * env, void * func, int32_t i);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_DefiningCFunction_upcallReturnLong1Param(PNIEnv_long * env, void * func, int64_t j);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_DefiningCFunction_upcallReturnShort1Param(PNIEnv_short * env, void * func, int16_t s);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_DefiningCFunction_upcallReturnPointer1Param(PNIEnv_pointer * env, void * func, void * p);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_DefiningCFunction
// metadata.generator-version: pni test
// sha256:170ab205e0aa723f1d17ce5cc6d4ef1f7d95b8810b08b0c661ab0ebb83dfb5c0
