/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCCompatibilityPacked */
#ifndef _Included_io_vproxy_pni_test_GCCCompatibilityPacked
#define _Included_io_vproxy_pni_test_GCCCompatibilityPacked
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "gcc_compatibility.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(GCCCompatibilityPacked, GCCCompatibilityPacked *)
PNIBufExpand(GCCCompatibilityPacked, GCCCompatibilityPacked, 27)

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityPacked_init(PNIEnv_void * env, GCCCompatibilityPacked * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityPacked_size(PNIEnv_long * env, GCCCompatibilityPacked * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCCompatibilityPacked
// metadata.generator-version: pni test
// sha256:5eb2b33909d39d2746616e8be840c9e4a56a40df62097da0cba5b2c0deba422d
