/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GrandChildClass */
#ifndef _Included_io_vproxy_pni_test_GrandChildClass
#define _Included_io_vproxy_pni_test_GrandChildClass
#ifdef __cplusplus
extern "C" {
#endif

struct GrandChildClass;
typedef struct GrandChildClass GrandChildClass;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_ChildClass.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(GrandChildClass, GrandChildClass *)
PNIBufExpand(GrandChildClass, GrandChildClass, 16)

struct GrandChildClass {
    ChildClass SUPER;
    int64_t y;
};

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GrandChildClass_yyy(PNIEnv_void * env, GrandChildClass * self, int64_t y);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GrandChildClass
// metadata.generator-version: pni test
// sha256:fdc5f7b3a18073047f9e41e1ebde280ef75dcedfed8ff8e5949518464b0aa340
