/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_PointerOnlyStructWithLen */
#ifndef _Included_io_vproxy_pni_test_PointerOnlyStructWithLen
#define _Included_io_vproxy_pni_test_PointerOnlyStructWithLen
#ifdef __cplusplus
extern "C" {
#endif

struct PointerOnlyStructWithLen;
typedef struct PointerOnlyStructWithLen PointerOnlyStructWithLen;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT size_t JNICALL JavaCritical_io_vproxy_pni_test_PointerOnlyStructWithLen___getLayoutByteSize();

PNIEnvExpand(PointerOnlyStructWithLen, PointerOnlyStructWithLen *)
PNIBufExpand(PointerOnlyStructWithLen, PointerOnlyStructWithLen, JavaCritical_io_vproxy_pni_test_PointerOnlyStructWithLen___getLayoutByteSize())

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_PointerOnlyStructWithLen
// metadata.generator-version: pni test
// sha256:b1de7af3b3ad8d35200b2af436bec581b33c939357a67c90d5b00db8ac3f3ff6
