/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_ChildClass */
#ifndef _Included_io_vproxy_pni_test_ChildClass
#define _Included_io_vproxy_pni_test_ChildClass
#ifdef __cplusplus
extern "C" {
#endif

struct ChildClass;
typedef struct ChildClass ChildClass;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_BaseClass.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(ChildClass, ChildClass *)
PNIBufExpand(ChildClass, ChildClass, 4)

struct ChildClass {
    BaseClass SUPER;
    int16_t x;
};

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_ChildClass_xxx(PNIEnv_void * env, ChildClass * self, int16_t x);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_ChildClass
// metadata.generator-version: pni test
// sha256:581ea055936898f03845462c7d9796fa4eb06d42163259ff64c55ab2cf27b28e
