/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_ToStringClass2 */
#ifndef _Included_io_vproxy_pni_test_ToStringClass2
#define _Included_io_vproxy_pni_test_ToStringClass2
#ifdef __cplusplus
extern "C" {
#endif

struct ToStringClass2;
typedef struct ToStringClass2 ToStringClass2;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(ToStringClass2, ToStringClass2 *)
PNIBufExpand(ToStringClass2, ToStringClass2, 40)

struct ToStringClass2 {
    int64_t num;
    PNIRef * ref;
    PNIFunc * func;
    PNIBuf_ToStringClass arrc;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_ToStringClass2
// metadata.generator-version: pni test
// sha256:96a6e336fa09af3abc9caf28762aacb825ef42dad11d7d5eb6ecc05887d09509
