/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_LargeAlignBase */
#ifndef _Included_io_vproxy_pni_test_LargeAlignBase
#define _Included_io_vproxy_pni_test_LargeAlignBase
#ifdef __cplusplus
extern "C" {
#endif

struct LargeAlignBase;
typedef struct LargeAlignBase LargeAlignBase;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(LargeAlignBase, LargeAlignBase *)
PNIBufExpand(LargeAlignBase, LargeAlignBase, 8)

struct LargeAlignBase {
    int64_t x;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_LargeAlignBase
// metadata.generator-version: pni test
// sha256:34d8a9813c4e536badc8f428939c0ea59147fa389aa92613c96f43af8520dc89
