/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_CustomNativeTypeUpcall */
#ifndef _Included_io_vproxy_pni_test_CustomNativeTypeUpcall
#define _Included_io_vproxy_pni_test_CustomNativeTypeUpcall
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "sizeof.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int64_t* JNICALL JavaCritical_io_vproxy_pni_test_CustomNativeTypeUpcall_exec(SizeofStructExpr* o);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_CustomNativeTypeUpcall
// metadata.generator-version: pni test
// sha256:7d124f76a574ad5ba3d54b0ce0874e3eb7b5be69e3aeb18943ef27898d0b17dd
