/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_AlwaysAlignedClass */
#ifndef _Included_io_vproxy_pni_test_AlwaysAlignedClass
#define _Included_io_vproxy_pni_test_AlwaysAlignedClass
#ifdef __cplusplus
extern "C" {
#endif

struct AlwaysAlignedClass;
typedef struct AlwaysAlignedClass AlwaysAlignedClass;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(AlwaysAlignedClass, AlwaysAlignedClass *)
PNIBufExpand(AlwaysAlignedClass, AlwaysAlignedClass, 16)

struct AlwaysAlignedClass {
    int8_t a;
    int16_t b;
    int64_t c;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_AlwaysAlignedClass
// metadata.generator-version: pni test
// sha256:368b8e4afa3468df3a3513c79046ff765f4c3a64af028c0f95e000ab5b733b9f
