/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_AlignChildClass */
#ifndef _Included_io_vproxy_pni_test_AlignChildClass
#define _Included_io_vproxy_pni_test_AlignChildClass
#ifdef __cplusplus
extern "C" {
#endif

struct AlignChildClass;
typedef struct AlignChildClass AlignChildClass;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_AlignBaseClass.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(AlignChildClass, AlignChildClass *)
PNIBufExpand(AlignChildClass, AlignChildClass, 32)

struct AlignChildClass {
    AlignBaseClass SUPER;
     /* padding */ uint16_t : 16; uint16_t : 16; uint16_t : 16; uint16_t : 16; uint16_t : 16; uint16_t : 16; uint16_t : 16;
    int32_t b;
    int32_t c; /* padding */ uint32_t : 32; uint32_t : 32;
};

JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_test_AlignChildClass_bbbb(AlignChildClass * self);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_pni_test_AlignChildClass_cccc(AlignChildClass * self);
JNIEXPORT int64_t JNICALL JavaCritical_io_vproxy_pni_test_AlignChildClass_size(AlignChildClass * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_AlignChildClass
// metadata.generator-version: pni test
// sha256:ce5a50d8241d49e1a5e99eb9da7bbc0f382aba84a65a6e7f6886da0ed9d070c0
