/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_Empty */
#ifndef _Included_io_vproxy_pni_test_Empty
#define _Included_io_vproxy_pni_test_Empty
#ifdef __cplusplus
extern "C" {
#endif

struct Empty;
typedef struct Empty Empty;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(Empty, Empty *)
PNIBufExpand(Empty, Empty, (0 /* !!invalid!! */))

struct Empty {
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_Empty
// metadata.generator-version: pni test
// sha256:06c1e7dc355b3f3d0310d1dde826f6691de5dcd88a995a77cf075edde176b9ca
