/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCCompatibilityUnion */
#ifndef _Included_io_vproxy_pni_test_GCCCompatibilityUnion
#define _Included_io_vproxy_pni_test_GCCCompatibilityUnion
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(GCCCompatibilityUnion, GCCCompatibilityUnion *)
PNIBufExpand(GCCCompatibilityUnion, GCCCompatibilityUnion, 8)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCCompatibilityUnion
// metadata.generator-version: pni test
// sha256:c6b63a10c2e7b205f33569fa36e5445bc0b8583ca4fe9386c027e80de46cf5cb
