/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_SizeofUnion */
#ifndef _Included_io_vproxy_pni_test_SizeofUnion
#define _Included_io_vproxy_pni_test_SizeofUnion
#ifdef __cplusplus
extern "C" {
#endif

union SizeofUnion;
typedef union SizeofUnion SizeofUnion;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_SizeofStruct.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT size_t JNICALL JavaCritical_io_vproxy_pni_test_SizeofUnion___getLayoutByteSize();

PNIEnvExpand(SizeofUnion, SizeofUnion *)
PNIBufExpand(SizeofUnion, SizeofUnion, JavaCritical_io_vproxy_pni_test_SizeofUnion___getLayoutByteSize())

union SizeofUnion {
    SizeofStruct st;
    int32_t a;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_SizeofUnion
// metadata.generator-version: pni test
// sha256:bf2bff254dd2de64affb49f03e1b9e9cdec09bd438e95e0d58307d59a6fc48d3
