/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_CustomNativeTypeStruct */
#ifndef _Included_io_vproxy_pni_test_CustomNativeTypeStruct
#define _Included_io_vproxy_pni_test_CustomNativeTypeStruct
#ifdef __cplusplus
extern "C" {
#endif

struct CustomNativeTypeStruct;
typedef struct CustomNativeTypeStruct CustomNativeTypeStruct;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "sizeof.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(CustomNativeTypeStruct, CustomNativeTypeStruct *)
PNIBufExpand(CustomNativeTypeStruct, CustomNativeTypeStruct, 32)

struct CustomNativeTypeStruct {
    SizeofStructExpr* field;
    SizeofStructExpr* array[3];
};

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_CustomNativeTypeStruct_getP1(PNIEnv_long * env, CustomNativeTypeStruct * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_CustomNativeTypeStruct_getArr(PNIEnv_buf_ptr * env, CustomNativeTypeStruct * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_CustomNativeTypeStruct
// metadata.generator-version: pni test
// sha256:685b91aa6222210de424b5a5ed7ebededbb003089f412bb1812c7e96c09c3901
