/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_UnionO */
#ifndef _Included_io_vproxy_pni_test_UnionO
#define _Included_io_vproxy_pni_test_UnionO
#ifdef __cplusplus
extern "C" {
#endif

union UnionO;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_UnionP.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(UnionO, union UnionO *)
PNIBufExpand(UnionO, union UnionO, 8)

union UnionO {
    int16_t s;
    int32_t i;
    UnionP p;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_UnionO
// metadata.generator-version: pni test
// sha256:1743a25ed3e78afb9b2e4382a0ccd59dc39462033a6260f112d66279ad72b096
