/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_UnionC */
#ifndef _Included_io_vproxy_pni_test_UnionC
#define _Included_io_vproxy_pni_test_UnionC
#ifdef __cplusplus
extern "C" {
#endif

union UnionC;
typedef union UnionC UnionC;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(UnionC, UnionC *)
PNIBufExpand(UnionC, UnionC, 8)

union UnionC {
    int32_t n;
    int64_t l;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_UnionC
// metadata.generator-version: pni test
// sha256:eda297c5239137523e1577fe3ffe6c9185b81f0f5db08aeaa6f575f0cd6b9f1a
