/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_AlwaysAlignedField */
#ifndef _Included_io_vproxy_pni_test_AlwaysAlignedField
#define _Included_io_vproxy_pni_test_AlwaysAlignedField
#ifdef __cplusplus
extern "C" {
#endif

struct AlwaysAlignedField;
typedef struct AlwaysAlignedField AlwaysAlignedField;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(AlwaysAlignedField, AlwaysAlignedField *)
PNIBufExpand(AlwaysAlignedField, AlwaysAlignedField, 16)

PNI_PACK(struct, AlwaysAlignedField, {
    int8_t a;
    int16_t b;
    int8_t c;
    int32_t d;
    int64_t e;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_AlwaysAlignedField
// metadata.generator-version: pni test
// sha256:3908caf32c762a3d0824066b57d97c64b934a381b14f6d678b33cfc3e66bbbff
