/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_ReferenceEmptyChild */
#ifndef _Included_io_vproxy_pni_test_ReferenceEmptyChild
#define _Included_io_vproxy_pni_test_ReferenceEmptyChild
#ifdef __cplusplus
extern "C" {
#endif

struct ReferenceEmptyChild;
typedef struct ReferenceEmptyChild ReferenceEmptyChild;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_EmptyChild.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(ReferenceEmptyChild, ReferenceEmptyChild *)
PNIBufExpand(ReferenceEmptyChild, ReferenceEmptyChild, 8)

struct ReferenceEmptyChild {
    EmptyChild emptyChild;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_ReferenceEmptyChild
// metadata.generator-version: pni test
// sha256:1add262979a6850e3090dea12125ad28b4f6691deda4da3a2d6871187c8d3262
