/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_StructB */
#ifndef _Included_io_vproxy_pni_test_StructB
#define _Included_io_vproxy_pni_test_StructB
#ifdef __cplusplus
extern "C" {
#endif

struct StructB;
typedef struct StructB StructB;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_UnionC.h"
#include "io_vproxy_pni_test_StructD.h"
#include "io_vproxy_pni_test_UnionEmbedded.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(StructB, StructB *)
PNIBufExpand(StructB, StructB, 40)

struct StructB {
    int32_t i;
    UnionC c;
    int64_t l;
    StructD * d;
    union {
        int32_t n;
        void * seg;
    };
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_StructB
// metadata.generator-version: pni test
// sha256:d90fc0ede1dd5b453c9d36c52ced018e743fce7d6833b6e5871c27efa0fb66fd
