/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_AlwaysAlignedChild */
#ifndef _Included_io_vproxy_pni_test_AlwaysAlignedChild
#define _Included_io_vproxy_pni_test_AlwaysAlignedChild
#ifdef __cplusplus
extern "C" {
#endif

struct AlwaysAlignedChild;
typedef struct AlwaysAlignedChild AlwaysAlignedChild;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_AlwaysAlignedBase.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(AlwaysAlignedChild, AlwaysAlignedChild *)
PNIBufExpand(AlwaysAlignedChild, AlwaysAlignedChild, 4)

struct AlwaysAlignedChild {
    AlwaysAlignedBase SUPER;
    int16_t b;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_AlwaysAlignedChild
// metadata.generator-version: pni test
// sha256:5f97a7f1270ceb12d002197a5f63e1f5b1fe0e7da5f9f11ab1d9c61cda8494f1
