/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_Null */
#ifndef _Included_io_vproxy_pni_test_Null
#define _Included_io_vproxy_pni_test_Null
#ifdef __cplusplus
extern "C" {
#endif

struct Null;
typedef struct Null Null;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_ObjectStruct.h"
#include "io_vproxy_pni_test_Null.h"
#include "io_vproxy_pni_test_Empty.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(Null, Null *)
PNIBufExpand(Null, Null, 216)

struct Null {
    ObjectStruct * o;
    char * str;
    void * seg;
    PNIBuf buf;
    PNIBuf_byte byteArr;
    PNIBuf_bool boolArr;
    PNIBuf_char charArr;
    PNIBuf_float floatArr;
    PNIBuf_double doubleArr;
    PNIBuf_int intArr;
    PNIBuf_long longArr;
    PNIBuf_short shortArr;
    PNIBuf_ObjectStruct oArr;
    PNIRef * ref;
    PNIFunc * func;
    PNIFunc * funcVoid;
    PNIFunc * funcRef;
};

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Null_testParam(PNIEnv_bool * env, Null * self, ObjectStruct * o, char * str, void * seg, PNIBuf * buf, PNIBuf_byte * byteArr, PNIBuf_bool * boolArr, PNIBuf_char * charArr, PNIBuf_float * floatArr, PNIBuf_double * doubleArr, PNIBuf_int * intArr, PNIBuf_long * longArr, PNIBuf_short * shortArr, PNIBuf_ObjectStruct * oArr, PNIRef * ref, PNIFunc * func, PNIFunc * funcVoid, PNIFunc * funcRef);
JNIEXPORT uint8_t JNICALL JavaCritical_io_vproxy_pni_test_Null_testParamCritical(Null * self, ObjectStruct * o, char * str, void * seg, PNIBuf * buf, PNIBuf_byte * byteArr, PNIBuf_bool * boolArr, PNIBuf_char * charArr, PNIBuf_float * floatArr, PNIBuf_double * doubleArr, PNIBuf_int * intArr, PNIBuf_long * longArr, PNIBuf_short * shortArr, PNIBuf_ObjectStruct * oArr, PNIRef * ref, PNIFunc * func, PNIFunc * funcVoid, PNIFunc * funcRef);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Null_testParamRaw(PNIEnv_bool * env, Null * self, void * buf, void * byteArr, uint8_t * boolArr, uint16_t * charArr, float * floatArr, double * doubleArr, int32_t * intArr, int64_t * longArr, int16_t * shortArr, ObjectStruct * oArr, PNIRef * ref, PNIFunc * func, PNIFunc * funcVoid, PNIFunc * funcRef);
JNIEXPORT uint8_t JNICALL JavaCritical_io_vproxy_pni_test_Null_testParamRawCritical(Null * self, void * buf, void * byteArr, uint8_t * boolArr, uint16_t * charArr, float * floatArr, double * doubleArr, int32_t * intArr, int64_t * longArr, int16_t * shortArr, ObjectStruct * oArr, PNIRef * ref, PNIFunc * func, PNIFunc * funcVoid, PNIFunc * funcRef);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Null_returnO(PNIEnv_ObjectStruct * env, Null * self, ObjectStruct * return_);
JNIEXPORT ObjectStruct * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnOCritical(Null * self, ObjectStruct * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Null_returnStr(PNIEnv_string * env, Null * self);
JNIEXPORT char * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnStrCritical(Null * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Null_returnSeg(PNIEnv_pointer * env, Null * self);
JNIEXPORT void * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnSegCritical(Null * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Null_returnBuf(PNIEnv_buf * env, Null * self);
JNIEXPORT PNIBuf * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnBufCritical(Null * self, PNIBuf * return_);
JNIEXPORT PNIBuf * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnBufCritical2(Null * self, PNIBuf * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Null_returnByteArr(PNIEnv_buf_byte * env, Null * self);
JNIEXPORT PNIBuf_byte * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnByteArrCritical(Null * self, PNIBuf_byte * return_);
JNIEXPORT PNIBuf_byte * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnByteArrCritical2(Null * self, PNIBuf_byte * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Null_returnBoolArr(PNIEnv_buf_bool * env, Null * self);
JNIEXPORT PNIBuf_bool * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnBoolArrCritical(Null * self, PNIBuf_bool * return_);
JNIEXPORT PNIBuf_bool * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnBoolArrCritical2(Null * self, PNIBuf_bool * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Null_returnCharArr(PNIEnv_buf_char * env, Null * self);
JNIEXPORT PNIBuf_char * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnCharArrCritical(Null * self, PNIBuf_char * return_);
JNIEXPORT PNIBuf_char * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnCharArrCritical2(Null * self, PNIBuf_char * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Null_returnFloatArr(PNIEnv_buf_float * env, Null * self);
JNIEXPORT PNIBuf_float * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnFloatArrCritical(Null * self, PNIBuf_float * return_);
JNIEXPORT PNIBuf_float * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnFloatArrCritical2(Null * self, PNIBuf_float * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Null_returnDoubleArr(PNIEnv_buf_double * env, Null * self);
JNIEXPORT PNIBuf_double * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnDoubleArrCritical(Null * self, PNIBuf_double * return_);
JNIEXPORT PNIBuf_double * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnDoubleArrCritical2(Null * self, PNIBuf_double * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Null_returnIntArr(PNIEnv_buf_int * env, Null * self);
JNIEXPORT PNIBuf_int * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnIntArrCritical(Null * self, PNIBuf_int * return_);
JNIEXPORT PNIBuf_int * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnIntArrCritical2(Null * self, PNIBuf_int * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Null_returnLongArr(PNIEnv_buf_long * env, Null * self);
JNIEXPORT PNIBuf_long * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnLongArrCritical(Null * self, PNIBuf_long * return_);
JNIEXPORT PNIBuf_long * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnLongArrCritical2(Null * self, PNIBuf_long * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Null_returnShortArr(PNIEnv_buf_short * env, Null * self);
JNIEXPORT PNIBuf_short * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnShortArrCritical(Null * self, PNIBuf_short * return_);
JNIEXPORT PNIBuf_short * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnShortArrCritical2(Null * self, PNIBuf_short * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Null_returnOArr(PNIEnv_buf_ObjectStruct * env, Null * self);
JNIEXPORT PNIBuf_ObjectStruct * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnOArrCritical(Null * self, PNIBuf_ObjectStruct * return_);
JNIEXPORT PNIBuf_ObjectStruct * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnOArrCritical2(Null * self, PNIBuf_ObjectStruct * return_);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Null_returnRef(PNIEnv_ref * env, Null * self);
JNIEXPORT PNIRef * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnRefCritical(Null * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Null_returnFunc(PNIEnv_func * env, Null * self);
JNIEXPORT PNIFunc * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnFuncCritical(Null * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Null_returnFuncVoid(PNIEnv_func * env, Null * self);
JNIEXPORT PNIFunc * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnFuncVoidCritical(Null * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Null_returnFuncRef(PNIEnv_func * env, Null * self);
JNIEXPORT PNIFunc * JNICALL JavaCritical_io_vproxy_pni_test_Null_returnFuncRefCritical(Null * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_Null_emptyPassThrough(PNIEnv_Empty * env, Null * self, Empty * empty, Empty * return_);
JNIEXPORT Empty * JNICALL JavaCritical_io_vproxy_pni_test_Null_emptyPassThroughCritical(Null * self, Empty * empty, Empty * return_);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_Null
// metadata.generator-version: pni test
// sha256:6d3d2172b41eadec22e7c97223e8fc0e75af8d370c71fb3ad0f0243d910bb1ba
