/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCCompatibilityPackedAlignField */
#ifndef _Included_io_vproxy_pni_test_GCCCompatibilityPackedAlignField
#define _Included_io_vproxy_pni_test_GCCCompatibilityPackedAlignField
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "gcc_compatibility.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(GCCCompatibilityPackedAlignField, GCCCompatibilityPackedAlignField *)
PNIBufExpand(GCCCompatibilityPackedAlignField, GCCCompatibilityPackedAlignField, 12)

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityPackedAlignField_init(PNIEnv_void * env, GCCCompatibilityPackedAlignField * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCCompatibilityPackedAlignField_size(PNIEnv_long * env, GCCCompatibilityPackedAlignField * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCCompatibilityPackedAlignField
// metadata.generator-version: pni test
// sha256:8ba13b98e2dec29732170ea31bcfdc65ee99c7ef09a6164d916b194a1ccc0138
