/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_ToStringClassRecurse */
#ifndef _Included_io_vproxy_pni_test_ToStringClassRecurse
#define _Included_io_vproxy_pni_test_ToStringClassRecurse
#ifdef __cplusplus
extern "C" {
#endif

struct ToStringClassRecurse;
typedef struct ToStringClassRecurse ToStringClassRecurse;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_ToStringClass.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(ToStringClassRecurse, ToStringClassRecurse *)
PNIBufExpand(ToStringClassRecurse, ToStringClassRecurse, 16)

struct ToStringClassRecurse {
    int64_t num;
    ToStringClass * c;
    int32_t arri[0];
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_ToStringClassRecurse
// metadata.generator-version: pni test
// sha256:0d7531717b9724eb6f9bb1f9c2588a3c1413b2a9ce6d0fdeac0d0ec7e613251c
