/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_GCCompatibilityStructAlign */
#ifndef _Included_io_vproxy_pni_test_GCCompatibilityStructAlign
#define _Included_io_vproxy_pni_test_GCCompatibilityStructAlign
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "gcc_compatibility.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(GCCompatibilityStructAlign, GCCompatibilityStructAlign *)
PNIBufExpand(GCCompatibilityStructAlign, GCCompatibilityStructAlign, 32)

JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCompatibilityStructAlign_init(PNIEnv_void * env, GCCompatibilityStructAlign * self);
JNIEXPORT int JNICALL Java_io_vproxy_pni_test_GCCompatibilityStructAlign_size(PNIEnv_long * env, GCCompatibilityStructAlign * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_GCCompatibilityStructAlign
// metadata.generator-version: pni test
// sha256:02834d3286891ba168c653a42ebb725059eed45f0b1513293ec48805d8f22e42
