/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_test_NoAllocUpcall */
#ifndef _Included_io_vproxy_pni_test_NoAllocUpcall
#define _Included_io_vproxy_pni_test_NoAllocUpcall
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_test_ObjectStruct.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT ObjectStruct * JNICALL JavaCritical_io_vproxy_pni_test_NoAllocUpcall_execNoAlloc(void);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_test_NoAllocUpcall
// metadata.generator-version: pni test
// sha256:49776a126bf2667e99ad34e42dfb3708f2a5f43ce6a95e2156f3e09cd196c2ab
