/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_sample_UserData */
#ifndef _Included_io_vproxy_pni_sample_UserData
#define _Included_io_vproxy_pni_sample_UserData
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_sample_UserData
// sha256:7dc067ef16b344c155692b89dd48ace8b0dbce876be96ccfa7be9f46941c2b36
