/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_sample_SampleFunctions */
#ifndef _Included_io_vproxy_pni_sample_SampleFunctions
#define _Included_io_vproxy_pni_sample_SampleFunctions
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_sample_MBuf.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int JNICALL Java_io_vproxy_pni_sample_SampleFunctions_read(PNIEnv_int * env, int32_t fd, mbuf_t * buf);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_sample_SampleFunctions
// metadata.generator-version: pni test
// sha256:a5dd7d7d43a0572718f6ea87f14e05f7cb34c283b1ab3af2e6d4add1f115ba47
