/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_sample_MBuf */
#ifndef _Included_io_vproxy_pni_sample_MBuf
#define _Included_io_vproxy_pni_sample_MBuf
#ifdef __cplusplus
extern "C" {
#endif

struct mbuf_t;
typedef struct mbuf_t mbuf_t;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_sample_UserData.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(mbuf_t, mbuf_t *)
PNIBufExpand(mbuf_t, mbuf_t, 32)

PNI_PACK(struct, mbuf_t, {
    void * bufAddr;
    uint32_t pktLen;
    uint32_t pktOff;
    uint32_t bufLen; /* padding */ uint64_t :32;
    union {
        void * userdata;
        uint64_t udata64;
    };
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_sample_MBuf
// metadata.generator-version: pni test
// sha256:6b6fba9a97491db9758eb4ca87380e967faea2b0364d3781525f81ec02ddee77
