/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_sample_NativeFunctions */
#ifndef _Included_io_vproxy_pni_sample_NativeFunctions
#define _Included_io_vproxy_pni_sample_NativeFunctions
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int JNICALL Java_io_vproxy_pni_sample_NativeFunctions_openIPv4TcpSocket(PNIEnv_int * env);
JNIEXPORT int JNICALL Java_io_vproxy_pni_sample_NativeFunctions_bindIPv4(PNIEnv_void * env, int32_t fd, int32_t ipv4, int32_t port);
JNIEXPORT int JNICALL Java_io_vproxy_pni_sample_NativeFunctions_listen(PNIEnv_void * env, int32_t fd, int32_t n);
JNIEXPORT int JNICALL Java_io_vproxy_pni_sample_NativeFunctions_accept(PNIEnv_int * env, int32_t fd);
JNIEXPORT int JNICALL Java_io_vproxy_pni_sample_NativeFunctions_close(PNIEnv_void * env, int32_t fd);
JNIEXPORT int JNICALL Java_io_vproxy_pni_sample_NativeFunctions_write(PNIEnv_int * env, int32_t fd, void * mem, int32_t off, int32_t len);
JNIEXPORT int JNICALL Java_io_vproxy_pni_sample_NativeFunctions_read(PNIEnv_int * env, int32_t fd, void * mem, int32_t off, int32_t len);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_sample_NativeFunctions
// sha256:800290cc79776a49826a0adb52d3d90799ac0cbe238dbbc6976d631e2626326f
