/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_pni_sample_MBuf */
#ifndef _Included_io_vproxy_pni_sample_MBuf
#define _Included_io_vproxy_pni_sample_MBuf
#ifdef __cplusplus
extern "C" {
#endif

struct mbuf_t;
typedef struct mbuf_t mbuf_t;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_pni_sample_UserData.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(mbuf_t, mbuf_t *)
PNIBufExpand(mbuf_t, mbuf_t, 32)

struct mbuf_t {
    void * bufAddr;
    uint32_t pktLen;
    uint32_t pktOff;
    uint32_t bufLen;
    union {
        void * userdata;
        uint64_t udata64;
    };
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_pni_sample_MBuf
// metadata.generator-version: pni test
// sha256:e513cbed641492f56d87b30e17e6bf6c2a3a074788c90a28dfd82bb294b05416
